# Generated by Django 6.0.8 on 2026-10-07 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0012_alter_answer_file_alter_assignmentsubmission_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspended', models.BooleanField(default=False, help_text='Hidden from review by the student.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='assessments.question')),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_cards', to='assessments.assessmentattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=5)),
                ('box_before', models.PositiveSmallIntegerField()),
                ('box_after', models.PositiveSmallIntegerField()),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='revision.reviewcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewcard',
            index=models.Index(fields=['user', 'suspended', 'due_at'], name='revision_re_user_id_012549_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewcard',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='uniq_review_card_per_user_question'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user', 'reviewed_at'], name='revision_re_user_id_f89947_idx'),
        ),
    ]
