# Generated by Django 6.0.7 on 2026-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('failed', 'Failed'), ('running', 'Running')], max_length=8)),
                ('last_output', models.TextField(blank=True)),
                ('last_duration_ms', models.PositiveIntegerField(default=0)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'scheduled job',
                'ordering': ['name'],
            },
        ),
    ]
