# Generated by Django 6.0.6 on 2026-07-01 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgtasks', '0001_initial'),
    ]

    operations = [
    ]
