# Generated by Django 6.0.6 on 2026-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgtasks', '0003_task_scorm_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.CharField(choices=[('user', 'A single user'), ('subject', 'A subject'), ('course', 'A course'), ('department', 'A department'), ('all', 'All users')], default='user', max_length=12),
        ),
    ]
