# Generated by Django 6.0.7 on 2026-07-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessment_status'),
        ('learning', '0011_lesson_target_roles'),
        ('orgtasks', '0004_remove_task_group_alter_task_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assessment',
            field=models.ForeignKey(blank=True, help_text='Deliver a quiz / test / assignment as this task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Deliver a lesson as this task; opening the task opens the lesson.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.lesson'),
        ),
    ]
