# Generated by Django 6.0.8 on 2026-08-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgtasks', '0005_task_assessment_task_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.CharField(choices=[('user', 'A single user'), ('subject', 'A subject'), ('course', 'A course'), ('all', 'All users')], default='user', max_length=12),
        ),
    ]
