# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
        ('orgtasks', '0006_remove_task_department_alter_task_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='learning.programmemodule'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.CharField(choices=[('user', 'A single user'), ('module', 'A module'), ('course', 'A course'), ('all', 'All users')], default='user', max_length=12),
        ),
    ]
