# Generated by Django 6.0.8 on 2026-08-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_remove_courseitemprogress_item_and_more'),
        ('orgtasks', '0007_remove_task_subject_task_module_alter_task_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.AddField(
            model_name='task',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Used when "Assign to" is a whole programme — every module under it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='learning.programme'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.CharField(choices=[('user', 'A single user'), ('module', 'A module'), ('programme', 'A whole programme'), ('all', 'All users')], default='user', max_length=12),
        ),
    ]
