# Generated by Django 6.0.6 on 2026-07-03 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parent_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('archived_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public — anyone signed in'), ('members', 'Members — people in my groups'), ('private', 'Private — only me')], default='members', help_text='Who may see your member profile page.', max_length=10)),
                ('show_email', models.BooleanField(default=False, help_text='Show your e-mail address on your profile.')),
                ('show_activity', models.BooleanField(default=True, help_text='Show your recent activity on your profile.')),
                ('allow_messages', models.BooleanField(default=True, help_text='Let other members start a direct chat with you.')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Match system')], default='auto', max_length=6)),
                ('language', models.CharField(choices=[('en', 'English'), ('af', 'Afrikaans'), ('zu', 'isiZulu'), ('xh', 'isiXhosa'), ('st', 'Sesotho'), ('fr', 'French'), ('pt', 'Portuguese')], default='en', max_length=8)),
                ('email_digest', models.CharField(choices=[('off', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', help_text='How often to bundle non-urgent e-mail.', max_length=8)),
                ('is_closing', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
