# Generated by Django 6.0.6 on 2026-07-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountarchive_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pending_invoice_uid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
