# Generated by Django 6.0.6 on 2026-07-04 20:27

from django.db import migrations, models


def to_student(apps, schema_editor):
    """Existing 'regular' / 'guest' users become 'student'."""
    Person = apps.get_model('accounts', 'Person')
    Person.objects.filter(user_type__in=['regular', 'guest']).update(user_type='student')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_person_pending_invoice_uid'),
    ]

    operations = [
        migrations.RunPython(to_student, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('staff', 'Staff'), ('parent', 'Parent'), ('educator', 'Educator')], default='student', max_length=20),
        ),
    ]
