# Generated by Django 6.0.6 on 2026-07-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_type_student'),
        ('myhub', '0002_event_owner_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='program',
            name='group',
        ),
        migrations.RemoveField(
            model_name='program',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='program',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course', 'name']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='myhub.course'),
        ),
    ]
