# Generated by Django 6.0.6 on 2026-07-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_group_leader_remove_group_members_and_more'),
        ('communication', '0007_remove_chatgroup_group_remove_chatgroup_program_and_more'),
        ('learning', '0003_remove_lesson_target_groups_and_more'),
        ('orgtasks', '0004_remove_task_group_alter_task_assign_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
