# Generated by Django 6.0.6 on 2026-07-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_group'),
        ('communication', '0007_remove_chatgroup_group_remove_chatgroup_program_and_more'),
        ('learning', '0003_remove_lesson_target_groups_and_more'),
        ('reports', '0003_remove_certificate_program_certificate_course'),
        ('shop', '0004_remove_product_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
