# Generated by Django 6.0.6 on 2026-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
