# Generated by Django 6.0.7 on 2026-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_person_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
