# Generated by Django 6.0.6 on 2026-07-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_personconsent_personcontact_personeducation_and_more'),
        ('myhub', '0003_course_additional_materials_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pending_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_people', to='myhub.course'),
        ),
    ]
