# Generated by Django 6.0.7 on 2026-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_parentlink_relationship_person_guardian_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeducation',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('correspond', 'Correspondence'), ('distance', 'Distance learning')], max_length=12),
        ),
    ]
