# Generated by Django 6.0.7 on 2026-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_person_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ms_upn',
            field=models.CharField(blank=True, max_length=255, verbose_name='Microsoft Teams UPN'),
        ),
    ]
