# Generated by Django 6.0.8 on 2026-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_person_ms_upn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='person',
            name='race',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='personstudyprofile',
            name='average_daily_study_hours',
        ),
        migrations.RemoveField(
            model_name='personstudyprofile',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='personstudyprofile',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='personstudyprofile',
            name='preferred_reminder_time',
        ),
        migrations.RemoveField(
            model_name='personstudyprofile',
            name='reason_for_course',
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, verbose_name='Area / suburb'),
        ),
    ]
