# Generated by Django 6.0.8 on 2026-08-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_person_address_remove_person_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
    ]
