# Generated by Django 6.0.7 on 2026-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_slim_registration_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountarchive',
            name='archive_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='accountarchive',
            name='content_rows',
            field=models.PositiveIntegerField(default=0, help_text='How many database rows were parked with this account.'),
        ),
        migrations.AddField(
            model_name='accountarchive',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='Set when an administrator restored this account back onto the live system.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français (French)'), ('pt', 'Português (Portuguese)')], default='en', max_length=8),
        ),
    ]
