# Generated by Django 6.0.8 on 2026-08-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_accountarchive_archive_dir_and_more'),
        ('ai_assistant', '0006_remove_aiinsight_subject_remove_aireport_subject_and_more'),
        ('analytics', '0002_remove_riskflag_subject_riskflag_module_and_more'),
        ('assessments', '0010_remove_assessment_subject_remove_exam_subject_and_more'),
        ('communication', '0019_remove_classsession_comm_session_subj_idx_and_more'),
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
        ('orgtasks', '0007_remove_task_subject_task_module_alter_task_assign_to'),
        ('reports', '0005_alter_grade_options_remove_certificate_subject_and_more'),
        ('shop', '0005_remove_product_subject_product_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
