# Generated by Django 6.0.8 on 2026-08-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_subject'),
        ('learning', '0023_remove_courseitemprogress_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='person',
            name='child_student',
        ),
        migrations.RemoveField(
            model_name='person',
            name='course',
        ),
        migrations.RemoveField(
            model_name='person',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pending_course',
        ),
        migrations.AddField(
            model_name='invitation',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_invites', to='learning.programme'),
        ),
    ]
