# Generated by Django 6.0.8 on 2026-08-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(blank=True, help_text='Your time zone. Session times, reminders and the calendar are shown in it. Blank = the platform default.', max_length=64),
        ),
    ]
