# Generated by Django 6.0.8 on 2026-08-18 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_usersettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='calendar_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
