# Generated by Django 6.0.8 on 2026-10-07 12:41

import apps.accounts.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_usersettings_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.profile_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif']), core.validators.MaxFileSize(2)]),
        ),
    ]
