# Generated by Django 6.0.8 on 2026-10-07 13:31

from django.conf import settings
from django.db import migrations


def copy_profile_names(apps, schema_editor):
    """Give every login the name on its profile (see apps.accounts.names)."""
    Person = apps.get_model('accounts', 'Person')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    for person in Person.objects.exclude(user__isnull=True).only('user_id', 'first_name', 'last_name').iterator():
        first, last = (person.first_name or '').strip()[:150], (person.last_name or '').strip()[:150]
        if first or last:
            User.objects.filter(pk=person.user_id).exclude(first_name=first, last_name=last) \
                .update(first_name=first, last_name=last)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_profile_picture_unique_names'),
    ]

    operations = [
        migrations.RunPython(copy_profile_names, migrations.RunPython.noop),
    ]
