# Generated by Django 6.0.9 on 2026-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_backfill_login_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, help_text="The school's own learner number (SA-SAMS admission / accession number).", max_length=20, verbose_name='Admission number'),
        ),
        migrations.AddField(
            model_name='person',
            name='lurits_number',
            field=models.CharField(blank=True, db_index=True, help_text='Learner Unit Record Information and Tracking System number issued by the DBE.', max_length=20, verbose_name='LURITS number'),
        ),
    ]
