# Generated by Django 6.0.6 on 2026-06-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payfast_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('online', 'Online'), ('payfast', 'PayFast'), ('cheque', 'Cheque')], default='online', max_length=20),
        ),
    ]
