# Generated by Django 6.0.8 on 2026-08-12 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_slim_registration_profile'),
        ('finance', '0004_alter_invoicepayment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, help_text='Image or PDF of the deposit slip / bank confirmation.', upload_to='payment_proofs/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('upload', 'Document uploaded by staff'), ('gateway', 'Settled by the payment gateway'), ('manual', 'Recorded by staff, no document')], db_index=True, default='upload', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='verified', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_on', models.DateField(blank=True, help_text='Date on the deposit slip.', null=True)),
                ('reference', models.CharField(blank=True, help_text='Bank reference, or the gateway payment id.', max_length=120)),
                ('note', models.TextField(blank=True, help_text='Anything staff need to remember about it.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('granted_months', models.PositiveSmallIntegerField(default=0, help_text='Months of module access granted off the back of this payment.')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='finance.invoice')),
                ('payment', models.ForeignKey(blank=True, help_text='The money record this proof supports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='finance.invoicepayment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='accounts.person')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs_recorded', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proof of payment',
                'verbose_name_plural': 'Proofs of payment',
                'ordering': ['-paid_on', '-created_at'],
                'indexes': [models.Index(fields=['person', '-created_at'], name='finance_pro_person__508c1c_idx')],
            },
        ),
    ]
