# Generated by Django 6.0.8 on 2026-08-17 15:15

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_proofofpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofpayment',
            name='document',
            field=models.FileField(blank=True, help_text='Image or PDF of the deposit slip / bank confirmation.', upload_to='payment_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
    ]
