# Generated by Django 6.0.8 on 2026-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_proofofpayment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of the line discounts, for display. Lines are already net of it.', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_inclusive',
            field=models.BooleanField(default=True, help_text='Line prices already include VAT (the VAT is extracted, not added).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT rate in percent. 0 = no VAT.', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='detail',
            field=models.CharField(blank=True, help_text='Second line under the description, e.g. "20% off".', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
