# Generated by Django 6.0.8 on 2026-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_commerce_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('online', 'Online'), ('payfast', 'PayFast'), ('cheque', 'Cheque'), ('credit', 'Account credit')], default='online', max_length=20),
        ),
    ]
