# Generated by Django 6.0.8 on 2026-09-28 10:43

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bookings'),
        ('learning', '0027_remove_moduleweek_topic_modulematerial_topic_and_more'),
        ('shop', '0013_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, help_text='Account code for your accountant, optional.', max_length=20)),
                ('group', models.CharField(choices=[('cost_of_sales', 'Cost of sales'), ('payroll', 'Staff & educators'), ('operating', 'Operating expenses'), ('other', 'Other expenses')], default='operating', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='footer',
            field=models.CharField(blank=True, help_text='Small print at the bottom.', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='P.O. / reference'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminders_sent',
            field=models.JSONField(blank=True, default=list, help_text='Automatic reminder stages already sent.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='summary',
            field=models.CharField(blank=True, help_text='One line under the title, e.g. "Semester 2 tuition".', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='First time the customer opened the pay link.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes / terms printed on the invoice.'),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='uniq_sequence_per_year')],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=40, unique=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('converted', 'Converted to invoice')], db_index=True, default='draft', max_length=10)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('po_number', models.CharField(blank=True, max_length=60, verbose_name='P.O. / reference')),
                ('notes', models.TextField(blank=True)),
                ('footer', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_estimate', to='finance.invoice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.estimate')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Profile name')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_treatment', models.CharField(choices=[('inclusive', 'Amount includes VAT'), ('none', 'No VAT')], default='inclusive', max_length=10, verbose_name='VAT')),
                ('paid_through', models.CharField(choices=[('bank', 'Business bank account'), ('card', 'Business card'), ('cash', 'Petty cash'), ('payfast', 'PayFast balance'), ('debit_order', 'Debit order'), ('owner', 'Paid personally (to reimburse)')], default='debit_order', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('every', models.PositiveSmallIntegerField(default=1, verbose_name='Repeat every')),
                ('frequency', models.CharField(choices=[('weekly', 'Week(s)'), ('monthly', 'Month(s)'), ('yearly', 'Year(s)')], default='monthly', max_length=8)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, help_text='Blank = never ends.', null=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='learning.institution')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring', to='finance.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total paid, in rand.', max_digits=12)),
                ('vat_treatment', models.CharField(choices=[('inclusive', 'Amount includes VAT'), ('none', 'No VAT')], default='inclusive', max_length=10, verbose_name='VAT')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_through', models.CharField(choices=[('bank', 'Business bank account'), ('card', 'Business card'), ('cash', 'Petty cash'), ('payfast', 'PayFast balance'), ('debit_order', 'Debit order'), ('owner', 'Paid personally (to reimburse)')], default='bank', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Reference #')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid (bill to pay)')], default='paid', max_length=8)),
                ('due_date', models.DateField(blank=True, help_text='For unpaid bills.', null=True)),
                ('receipt', models.FileField(blank=True, upload_to='expenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)])),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, help_text='Cost centre. Blank = the whole business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='learning.institution')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.recurringexpense')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.vendor')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
