# Generated by Django 6.0.9 on 2026-10-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_seed_expense_categories'),
        ('learning', '0029_ucs_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fee_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Months of school fees this invoice covers (0 = not a fees invoice).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='learning.programme', verbose_name='Grade (school fees)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_start',
            field=models.DateField(blank=True, help_text='First month of school fees this invoice covers.', null=True),
        ),
    ]
