# Generated by Django 6.0.6 on 2026-07-01 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_component_alter_assessment_kind'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('heading', 'Section heading'), ('lesson', 'Lesson'), ('assessment', 'Assessment / quiz')], default='lesson', max_length=12)),
                ('title', models.CharField(blank=True, help_text='Overrides the linked content title when set.', max_length=200)),
                ('is_required', models.BooleanField(default=True, help_text='Counts toward course completion.')),
                ('gate_next', models.BooleanField(default=False, help_text='Learner must finish this before the next item unlocks.')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='assessments.assessment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='learning.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.module')),
            ],
            options={
                'ordering': ['module', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.moduleitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_item_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item', 'student')},
            },
        ),
    ]
