# Generated by Django 6.0.6 on 2026-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_moduleitem_moduleitemprogress'),
        ('myhub', '0002_event_owner_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='target_groups',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='target_programs',
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_courses',
            field=models.ManyToManyField(blank=True, related_name='targeted_lessons', to='myhub.course'),
        ),
    ]
