# Generated by Django 6.0.6 on 2026-07-07 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_answer_feedback_answer_marked_answer_marked_by_and_more'),
        ('communication', '0009_connectionrequest'),
        ('learning', '0003_remove_lesson_target_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/authors/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='author_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lesson',
            name='author_role',
            field=models.CharField(blank=True, help_text='e.g. "Senior Lecturer, Physics".', max_length=160),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/covers/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=models.TextField(blank=True, help_text='Legacy rich-text content (block editor preferred).'),
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('embed', 'Embedded page / link'), ('file', 'File / download'), ('reference', 'Reference'), ('quiz', 'Quiz / test'), ('meeting', 'Live session'), ('callout', 'Callout'), ('divider', 'Divider')], default='text', max_length=12)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('media', models.FileField(blank=True, null=True, upload_to='lessons/blocks/')),
                ('track', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='assessments.assessment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='learning.lesson')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='communication.meetingroom')),
            ],
            options={
                'ordering': ['lesson', 'order'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='learning_le_lesson__ffefa1_idx')],
            },
        ),
    ]
