# Generated by Django 6.0.6 on 2026-07-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_author_avatar_lesson_author_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonblock',
            options={'ordering': ['order', 'id']},
        ),
    ]
