# Generated by Django 6.0.6 on 2026-07-07 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_lessonblock_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('embed', 'Embedded page / link'), ('file', 'File / download'), ('reference', 'Reference'), ('quiz', 'Quiz / test'), ('meeting', 'Live session'), ('callout', 'Callout'), ('divider', 'Divider')], default='text', max_length=12),
        ),
        migrations.AlterField(
            model_name='moduleitem',
            name='item_type',
            field=models.CharField(choices=[('heading', 'Section heading'), ('lesson', 'Lesson'), ('assessment', 'Assessment / quiz')], default='lesson', max_length=12),
        ),
    ]
