# Generated by Django 6.0.6 on 2026-07-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_lessonblock_h5p_moduleitem_h5p_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonresource',
            options={'ordering': ['lesson_id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='lessonversion',
            options={'ordering': ['lesson_id', '-version']},
        ),
    ]
