# Generated by Django 6.0.6 on 2026-07-16 03:11

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_lessonresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='media',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='lessons/blocks/'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='lessons/'),
        ),
    ]
