# Generated by Django 6.0.7 on 2026-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_lessonblock_media_alter_lessonresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('embed', 'Embedded page / link'), ('file', 'File / download'), ('reference', 'Reference'), ('quiz', 'Quiz / test'), ('meeting', 'Live session'), ('callout', 'Callout'), ('table', 'Table'), ('diagram', 'Diagram'), ('divider', 'Divider')], default='text', max_length=12),
        ),
    ]
