# Generated by Django 6.0.7 on 2026-07-24 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_lessonblock_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='New section', max_length=200)),
                ('summary', models.CharField(blank=True, help_text='One line shown under the title when the section is open.', max_length=300)),
                ('section_type', models.CharField(choices=[('auto', 'Auto — detect from content'), ('reading', 'Reading'), ('video', 'Video'), ('quiz', 'Quiz'), ('assessment', 'Assessment'), ('live', 'Live session'), ('interactive', 'Interactive'), ('resources', 'Resources')], default='auto', max_length=12)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='0 = estimate automatically.')),
                ('is_required', models.BooleanField(default=True, help_text='Counts toward lesson completion.')),
                ('requires_previous', models.BooleanField(default=False, help_text='Locked until every earlier required section is completed.')),
                ('open_by_default', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.lessonsection')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('section', 'Section'), ('text', 'Passage'), ('media', 'Moment in media'), ('question', 'Question')], default='text', max_length=10)),
                ('label', models.CharField(blank=True, help_text='What was saved (excerpt / timestamp).', max_length=300)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('anchor', models.JSONField(blank=True, default=dict)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='learning.lessonblock')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='learning.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='learning.lessonsection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='learning.lessonsection'),
        ),
        migrations.CreateModel(
            name='LessonSectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('seconds_spent', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.lessonsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_section_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='lessonsection',
            index=models.Index(fields=['lesson', 'order'], name='learning_le_lesson__b17a37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonnote',
            unique_together={('lesson', 'section', 'student')},
        ),
        migrations.AddIndex(
            model_name='lessonbookmark',
            index=models.Index(fields=['lesson', 'student'], name='learning_le_lesson__dfa802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsectionprogress',
            unique_together={('section', 'student')},
        ),
    ]
