# Generated by Django 6.0.7 on 2026-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_lessonsection_lessonnote_lessonbookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
