# Generated by Django 6.0.7 on 2026-07-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_lesson_target_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='holds_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchor_block', to='learning.lessonsection'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='style',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('embed', 'Embedded page / link'), ('file', 'File / download'), ('reference', 'Reference'), ('quiz', 'Quiz / test'), ('meeting', 'Live session'), ('callout', 'Callout'), ('table', 'Table'), ('diagram', 'Diagram'), ('divider', 'Divider'), ('section', 'Dropdown section')], default='text', max_length=12),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='learning.lessonsection'),
        ),
    ]
