# Generated by Django 6.0.8 on 2026-08-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_person_address_remove_person_bio_and_more'),
        ('learning', '0015_cta_academic_spine'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmemodule',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly price (ZAR) to study this module. 0 = free / always unlocked.', max_digits=8),
        ),
        migrations.CreateModel(
            name='ModuleEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('locked', 'Locked — awaiting payment'), ('trial', 'Free trial'), ('active', 'Active — paid'), ('expired', 'Expired')], db_index=True, default='locked', max_length=10)),
                ('price_at_enrolment', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price captured at enrolment (so later price changes do not rewrite history).', max_digits=8)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateField(blank=True, help_text='Access is paid up to this date.', null=True)),
                ('invoice_uid', models.UUIDField(blank=True, help_text='public_id of the invoice raised for this module.', null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_enrolments', to='accounts.person')),
                ('programme_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='learning.programmemodule')),
            ],
            options={
                'verbose_name': 'Module enrolment',
                'ordering': ['programme_module', 'person'],
                'constraints': [models.UniqueConstraint(fields=('person', 'programme_module'), name='uniq_module_enrolment_per_person')],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='learning.cohort')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_enrolments', to='accounts.person')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='learning.programme')),
            ],
            options={
                'verbose_name': 'Programme enrolment',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('person', 'programme'), name='uniq_programme_enrolment_per_person')],
            },
        ),
    ]
