# Generated by Django 6.0.8 on 2026-08-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_programmemodule_price_per_month_moduleenrolment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Academic year, e.g. 2026.')),
                ('name', models.CharField(blank=True, help_text='Blank = "<Institution> · <year> academic calendar".', max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='learning.institution')),
            ],
            options={
                'verbose_name': 'Academic calendar',
                'ordering': ['-year', 'institution'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('test', 'Test'), ('exam', 'Examination'), ('supp', 'Supplementary / re-assessment'), ('assignment', 'Assignment due'), ('deadline', 'Administrative deadline'), ('session', 'Coaching session'), ('intensive', 'Test / exam intensive'), ('mock', 'Mock assessment'), ('result', 'Results released'), ('orientation', 'Orientation'), ('holiday', 'Holiday / no session'), ('other', 'Other')], db_index=True, default='other', max_length=12)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True, help_text='A published date with no fixed time — most institution dates.')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Contribution to the final mark, if published.', max_digits=5, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished events are visible to staff only.')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='learning.academiccalendar')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='learning.cohort')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='learning.programme')),
                ('programme_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='learning.programmemodule', verbose_name='Module offering')),
            ],
            options={
                'verbose_name': 'Calendar event',
                'ordering': ['start', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='academiccalendar',
            constraint=models.UniqueConstraint(fields=('institution', 'year'), name='uniq_calendar_per_institution_year'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['calendar', 'start'], name='learning_ca_calenda_74b2f4_idx'),
        ),
    ]
