# Generated by Django 6.0.8 on 2026-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_slim_registration_profile'),
        ('learning', '0017_academiccalendar_calendarevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmemodule',
            name='educators',
            field=models.ManyToManyField(blank=True, help_text='Coaches who teach this offering.', limit_choices_to={'user_type__in': ['educator', 'staff', 'admin']}, related_name='taught_modules', to='accounts.person'),
        ),
    ]
