# Generated by Django 6.0.8 on 2026-08-12 13:35

from django.db import migrations, models


def fill_abbreviation(apps, schema_editor):
    """Existing programmes get their code as the abbreviation, and any that never
    had a full title get one from their short name — so nothing renders as a bare
    "(PGDA)" the first time the new display name is used."""
    Programme = apps.get_model('learning', 'Programme')
    for programme in Programme.objects.all():
        fields = []
        if not programme.abbreviation:
            programme.abbreviation = (programme.code or '')[:30]
            fields.append('abbreviation')
        if not programme.full_name:
            programme.full_name = programme.name or programme.code
            fields.append('full_name')
        if fields:
            programme.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_programmemodule_educators'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, help_text='Short form shown in brackets after the full name, e.g. "PGDA". Blank = use the code.', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full title, e.g. "Postgraduate Diploma in Accounting". Shown with the abbreviation after it everywhere the programme is named.', max_length=250),
        ),
        migrations.RunPython(fill_abbreviation, migrations.RunPython.noop),
    ]
