# Generated by Django 6.0.8 on 2026-08-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_programme_abbreviation_alter_programme_full_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['calendar', 'kind', 'start'], name='learning_calev_cal_kind_start'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['programme', 'start'], name='learning_calev_prog_start'),
        ),
    ]
