# Generated by Django 6.0.7 on 2026-08-13 10:44

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_assessment_kind'),
        ('communication', '0018_whatsappmessage'),
        ('learning', '0020_calendar_event_lookup_indexes'),
        ('shop', '0004_remove_product_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programmemodule',
            name='chat_group',
            field=models.OneToOneField(blank=True, help_text='Group chat for everyone studying this offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_module', to='communication.chatgroup'),
        ),
        migrations.CreateModel(
            name='ModulePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('test', 'Test preparation'), ('exam', 'Examination preparation'), ('supp', 'Supplementary preparation'), ('other', 'Other')], db_index=True, default='test', max_length=8)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Which test/exam this prepares for — 1–4 for tests, 1–2 for exams.')),
                ('title', models.CharField(blank=True, help_text='Blank = built from kind + sequence ("Test 2 preparation").', max_length=160)),
                ('summary', models.CharField(blank=True, help_text='One line on what this block covers.', max_length=300)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished blocks are visible to staff only.')),
                ('is_active', models.BooleanField(default=True)),
                ('calendar_event', models.ForeignKey(blank=True, help_text='The test/exam on the academic calendar this prepares for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_phases', to='learning.calendarevent')),
                ('programme_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='learning.programmemodule', verbose_name='Module offering')),
            ],
            options={
                'verbose_name': 'Module phase',
                'ordering': ['programme_module', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Week number within this phase.')),
                ('title', models.CharField(blank=True, help_text='Blank = the topic\'s name, else "Week n".', max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='learning.modulephase')),
                ('topic', models.ForeignKey(blank=True, help_text='The study-guide topic covered this week.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_weeks', to='learning.topic')),
            ],
            options={
                'verbose_name': 'Module week',
                'ordering': ['phase', 'order', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('blueprint', 'Blueprint'), ('study_guide', 'Topic study guide'), ('questions', 'Questions'), ('answers', 'Answers / solutions'), ('mock_exam', 'Mock exam / past paper'), ('assessment', 'Assessment'), ('live', 'Live session'), ('recording', 'Recording'), ('document', 'Document')], db_index=True, default='document', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='modules/materials/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('available_from', models.DateTimeField(blank=True, help_text='Hidden from students until this moment.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_preview', models.BooleanField(default=False, help_text='Open to everyone, even on a locked module — the taster.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_materials', to='assessments.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_materials', to='learning.lesson')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_materials', to='communication.meetingroom')),
                ('product', models.ForeignKey(blank=True, help_text='Set when this item is also sold on its own in the shop.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_materials', to='shop.product')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.modulephase')),
                ('week', models.ForeignKey(blank=True, help_text='Leave blank for material that covers the whole phase (e.g. the test blueprint).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.moduleweek')),
            ],
            options={
                'verbose_name': 'Module material',
                'ordering': ['phase', 'week', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='modulephase',
            constraint=models.UniqueConstraint(fields=('programme_module', 'kind', 'sequence'), name='uniq_phase_per_module'),
        ),
        migrations.AddConstraint(
            model_name='moduleweek',
            constraint=models.UniqueConstraint(fields=('phase', 'number'), name='uniq_week_per_phase'),
        ),
        migrations.AddIndex(
            model_name='modulematerial',
            index=models.Index(fields=['phase', 'kind'], name='learning_material_phase_kind'),
        ),
    ]
