# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_programmemodule_chat_group_modulephase_moduleweek_and_more'),
    ]

    operations = [
        # `learning_lesson` carried a `module_id` column once before: migration
        # 0002 created it, and 0014 renamed the COLUMN to `unit_id` — but Postgres
        # kept the index under its original `..._module_id_...` name. Adding a new
        # `module` FK below wants that exact name again, so on a fresh database the
        # replay collides. Retire the stale name first; IF EXISTS keeps this a
        # no-op on databases that never had it.
        migrations.RunSQL(
            sql=('ALTER INDEX IF EXISTS learning_lesson_module_id_c93351e5 '
                 'RENAME TO learning_lesson_unit_id_legacy_idx;'),
            reverse_sql=('ALTER INDEX IF EXISTS learning_lesson_unit_id_legacy_idx '
                         'RENAME TO learning_lesson_module_id_c93351e5;'),
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'unit', 'title']},
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='target_subjects',
        ),
        migrations.AddField(
            model_name='courseunit',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_modules',
            field=models.ManyToManyField(blank=True, related_name='targeted_lessons', to='learning.programmemodule'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='visibility',
            field=models.CharField(choices=[('institution', 'Entire institution'), ('program', 'Specific program'), ('class', 'Specific class'), ('module', 'Specific module'), ('group', 'Study group'), ('individual', 'Individual students')], default='module', max_length=12),
        ),
    ]
