# Generated by Django 6.0.8 on 2026-08-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_remove_assessment_unit'),
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
    ]

    operations = [
        # Clear the composite index BEFORE dropping either column it names —
        # Django resolves `unique_together` against the *current* model state,
        # and a removed field has no column to delete the index by.
        migrations.AlterUniqueTogether(
            name='courseitemprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseitemprogress',
            name='item',
        ),
        migrations.RemoveField(
            model_name='courseitemprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'title']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='target_courses',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='visibility',
            field=models.CharField(choices=[('institution', 'Entire institution'), ('programme', 'Specific programme'), ('module', 'Specific module'), ('group', 'Study group'), ('individual', 'Individual students')], default='module', max_length=12),
        ),
        migrations.DeleteModel(
            name='CourseItem',
        ),
        migrations.DeleteModel(
            name='CourseItemProgress',
        ),
        migrations.DeleteModel(
            name='CourseUnit',
        ),
    ]
