# Generated by Django 6.0.8 on 2026-08-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_remove_courseitemprogress_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulematerial',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Stable key from the content pack that placed this.', max_length=140),
        ),
    ]
