# Generated by Django 6.0.8 on 2026-08-17 15:15

import core.storage
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_modulematerial_source_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif']), core.validators.MaxFileSize(5)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/authors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif']), core.validators.MaxFileSize(2)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif']), core.validators.MaxFileSize(5)]),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='media',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='lessons/blocks/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif', 'mp3', 'wav', 'm4a', 'ogg', 'mp4', 'webm', 'mov', 'm4v']), core.validators.MaxFileSize(100)]),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='lessons/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
        migrations.AlterField(
            model_name='modulematerial',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='modules/materials/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
    ]
