# Generated by Django 6.0.8 on 2026-08-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_alter_institution_logo_alter_lesson_author_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulephase',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Which intake this block is for. Blank = shared by every cohort of the module.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_phases', to='learning.cohort'),
        ),
    ]
