# Generated by Django 6.0.8 on 2026-08-24, then hand-edited to preserve data.
#
# A week used to point at ONE topic (ModuleWeek.topic). It now works through a
# SERIES of topics via the WeekTopic through-model. This migration adds the new
# structures, COPIES each existing week.topic into a WeekTopic row (and stamps the
# week's materials with that topic) while the old column still exists, and only
# then drops ModuleWeek.topic. Reversible: the reverse restores week.topic from the
# first WeekTopic of each week.

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    ModuleWeek = apps.get_model('learning', 'ModuleWeek')
    WeekTopic = apps.get_model('learning', 'WeekTopic')
    ModuleMaterial = apps.get_model('learning', 'ModuleMaterial')
    for week in ModuleWeek.objects.filter(topic__isnull=False):
        WeekTopic.objects.get_or_create(week=week, topic_id=week.topic_id,
                                        defaults={'order': 0})
        # A single-topic week's materials all belong to that topic.
        ModuleMaterial.objects.filter(week=week, topic__isnull=True).update(topic_id=week.topic_id)


def backward(apps, schema_editor):
    # RemoveField is reversed first (re-adds the null topic column), so it exists here.
    ModuleWeek = apps.get_model('learning', 'ModuleWeek')
    WeekTopic = apps.get_model('learning', 'WeekTopic')
    for week in ModuleWeek.objects.all():
        first = WeekTopic.objects.filter(week=week).order_by('order', 'id').first()
        if first:
            week.topic_id = first.topic_id
            week.save(update_fields=['topic'])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_modulephase_cohort'),
    ]

    operations = [
        # 1) Additive changes first — the old moduleweek.topic column still exists.
        migrations.AddField(
            model_name='modulematerial',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Which topic within the week this material belongs to. Blank = it covers the whole week/phase, not one topic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='learning.topic'),
        ),
        migrations.AlterField(
            model_name='moduleweek',
            name='title',
            field=models.CharField(blank=True, help_text='Blank = the topics\' names, else "Week n".', max_length=200),
        ),
        migrations.CreateModel(
            name='WeekTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of this topic within the week.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_links', to='learning.topic')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_topics', to='learning.moduleweek')),
            ],
            options={
                'verbose_name': 'Week topic',
                'ordering': ['week', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='moduleweek',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='The study-guide topics covered this week, in order.', related_name='in_weeks', through='learning.WeekTopic', to='learning.topic'),
        ),
        migrations.AddConstraint(
            model_name='weektopic',
            constraint=models.UniqueConstraint(fields=('week', 'topic'), name='uniq_topic_per_week'),
        ),
        # 2) Copy the old single-topic data into the new structures.
        migrations.RunPython(forward, backward),
        # 3) Only now drop the old column.
        migrations.RemoveField(
            model_name='moduleweek',
            name='topic',
        ),
    ]
