# Generated by Django 6.0.9 on 2026-10-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_backfill_login_names'),
        ('learning', '0027_remove_moduleweek_topic_modulematerial_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='annual_levy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual levy, due on enrolment and settled in full by 25 January.', max_digits=8),
        ),
        migrations.AddField(
            model_name='programme',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='The grade number, 1 – 12.', null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly school fees, payable in advance on the 1st, January to December. 0 = no fees (subjects always unlocked).', max_digits=8),
        ),
        migrations.AddField(
            model_name='programme',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Once-off registration fee for a NEW learner (non-refundable). 0 = none.', max_digits=8),
        ),
        migrations.AddField(
            model_name='programmemodule',
            name='subject_group',
            field=models.CharField(blank=True, choices=[('', 'Compulsory'), ('fal', 'First Additional Language (choose one)'), ('maths', 'Mathematics or Mathematical Literacy (choose one)'), ('elective', 'Elective (choose three)')], default='', help_text='Grade 10 – 12 subject choice: blank = compulsory for every learner in the grade.', max_length=12),
        ),
        migrations.AlterField(
            model_name='institution',
            name='accent_colour',
            field=models.CharField(blank=True, default='#1F3864', help_text='Hex colour used for this school across the LMS.', max_length=9),
        ),
        migrations.AlterField(
            model_name='institution',
            name='accent_name',
            field=models.CharField(blank=True, help_text='e.g. "UCS Navy".', max_length=40),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(help_text='School code used throughout — "UCS".', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(help_text='Canonical code, e.g. "MATH" or "ENG-HL".', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='What the subject covers.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_competency_area',
            field=models.BooleanField(default=False, help_text='A competency area rather than an examined subject.'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, help_text='Short form shown in brackets after the full name. Blank = use the code.', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='code',
            field=models.CharField(help_text='Short code, e.g. "GR05". Prefixed with the school code to give the full code, "UCS-GR05".', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='depth_default',
            field=models.CharField(choices=[('FND', 'Foundational — core concepts and basic application'), ('ADV', 'Grade level — full CAPS depth for the grade'), ('INT', 'Extension — enrichment and cross-subject application'), ('UG', 'Support — remedial, below grade level')], default='ADV', help_text='Depth this grade is normally pitched at.', max_length=4),
        ),
        migrations.AlterField(
            model_name='programme',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full title, e.g. "Grade 5". Shown everywhere the grade is named.', max_length=250),
        ),
        migrations.AlterField(
            model_name='programme',
            name='is_competency_based',
            field=models.BooleanField(default=False, help_text='Structured around competency areas rather than examined subjects.'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('foundation', 'Foundation Phase (Grade 1 – 3)'), ('intermediate', 'Intermediate Phase (Grade 4 – 6)'), ('senior', 'Senior Phase (Grade 7 – 9)'), ('fet', 'FET Phase (Grade 10 – 12)')], db_index=True, default='foundation', help_text='CAPS phase.', max_length=16),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(help_text='Short display name, e.g. "Grade 5".', max_length=160),
        ),
        migrations.AlterField(
            model_name='programmemodule',
            name='code',
            field=models.CharField(help_text='The subject\'s code in this grade, e.g. "MATH".', max_length=20),
        ),
        migrations.AlterField(
            model_name='programmemodule',
            name='depth_level',
            field=models.CharField(blank=True, choices=[('FND', 'Foundational — core concepts and basic application'), ('ADV', 'Grade level — full CAPS depth for the grade'), ('INT', 'Extension — enrichment and cross-subject application'), ('UG', 'Support — remedial, below grade level')], help_text="Blank = inherit the programme's default depth.", max_length=4),
        ),
        migrations.AlterField(
            model_name='programmemodule',
            name='educators',
            field=models.ManyToManyField(blank=True, help_text='Teachers who teach this subject in this grade.', limit_choices_to={'user_type__in': ['educator', 'staff', 'admin']}, related_name='taught_modules', to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='programmemodule',
            name='name',
            field=models.CharField(blank=True, help_text='Overrides the canonical subject name when this grade names it differently.', max_length=160),
        ),
        migrations.AlterField(
            model_name='programmemodule',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Extra monthly price (ZAR) for this subject on top of the grade's school fees. Normally 0.", max_digits=8),
        ),
        migrations.AlterField(
            model_name='topic',
            name='depth',
            field=models.CharField(blank=True, choices=[('FND', 'Foundational — core concepts and basic application'), ('ADV', 'Grade level — full CAPS depth for the grade'), ('INT', 'Extension — enrichment and cross-subject application'), ('UG', 'Support — remedial, below grade level')], help_text="Blank = inherit the offering's depth.", max_length=4),
        ),
    ]
