# Generated by Django 6.0.9 on 2026-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_school_grades_and_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulematerial',
            name='kind',
            field=models.CharField(choices=[('blueprint', 'Assessment guide'), ('study_guide', 'Topic study guide'), ('questions', 'Questions'), ('answers', 'Answers / solutions'), ('mock_exam', 'Mock exam / past paper'), ('assessment', 'Assessment'), ('live', 'Live session'), ('recording', 'Recording'), ('document', 'Document')], db_index=True, default='document', max_length=12),
        ),
    ]
