# Generated by Django 6.0.9 on 2026-10-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_backfill_login_names'),
        ('learning', '0029_ucs_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher: takes the daily register and records promotion decisions.', limit_choices_to={'user_type__in': ['educator', 'staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='code',
            field=models.CharField(help_text='e.g. "2026" (the year) or "10A".', max_length=30),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. "Grade 10 · 2026".', max_length=120),
        ),
    ]
