# Generated by Django 6.0.9 on 2026-10-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_cohort_class_teacher_alter_cohort_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['programme', '-start_date', 'code'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['order', 'name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='moduleenrolment',
            options={'ordering': ['programme_module', 'person'], 'verbose_name': 'Subject enrolment'},
        ),
        migrations.AlterModelOptions(
            name='modulematerial',
            options={'ordering': ['phase', 'week', 'order', 'id'], 'verbose_name': 'Subject material'},
        ),
        migrations.AlterModelOptions(
            name='modulephase',
            options={'ordering': ['programme_module', 'order', 'id'], 'verbose_name': 'Subject term / block'},
        ),
        migrations.AlterModelOptions(
            name='moduleweek',
            options={'ordering': ['phase', 'order', 'number', 'id'], 'verbose_name': 'Subject week'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['institution', 'order', 'name'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='programmeenrolment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grade enrolment'},
        ),
        migrations.AlterModelOptions(
            name='programmemodule',
            options={'ordering': ['programme', 'order', 'id'], 'verbose_name': 'Grade subject'},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='programme_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='learning.programmemodule', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='modulematerial',
            name='kind',
            field=models.CharField(choices=[('blueprint', 'Assessment guide'), ('study_guide', 'Topic study guide'), ('questions', 'Questions'), ('answers', 'Answers / solutions'), ('mock_exam', 'Practice exam / past paper'), ('assessment', 'Assessment'), ('live', 'Live session'), ('recording', 'Recording'), ('document', 'Document')], db_index=True, default='document', max_length=12),
        ),
        migrations.AlterField(
            model_name='modulephase',
            name='kind',
            field=models.CharField(choices=[('term', 'School term'), ('test', 'Test preparation'), ('exam', 'Examination preparation'), ('supp', 'Supplementary / revision'), ('other', 'Other')], db_index=True, default='test', max_length=8),
        ),
        migrations.AlterField(
            model_name='modulephase',
            name='programme_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='learning.programmemodule', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='modulephase',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which term (1–4), or which test/exam this prepares for.'),
        ),
        migrations.AlterField(
            model_name='modulephase',
            name='title',
            field=models.CharField(blank=True, help_text='Blank = built from kind + sequence ("Term 2").', max_length=160),
        ),
    ]
