# Generated by Django 6.0.7 on 2026-07-28 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Catalog code, e.g. CERT-8001.', max_length=16)),
                ('fingerprint', models.CharField(db_index=True, max_length=40, unique=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=10)),
                ('message', models.TextField(blank=True, help_text='The exception text or log message.')),
                ('exception_type', models.CharField(blank=True, max_length=120)),
                ('traceback', models.TextField(blank=True, help_text='Most recent occurrence only.')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Structured extras the reporting site attached.')),
                ('module', models.CharField(blank=True, db_index=True, max_length=200)),
                ('function', models.CharField(blank=True, max_length=200)),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, help_text='Request path, when there was one.', max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('view_name', models.CharField(blank=True, max_length=200)),
                ('user_label', models.CharField(blank=True, help_text='Kept as text so the row survives account deletion.', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(db_index=True, default=1)),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ack', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Developer notes on this error.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=12)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'error event',
                'verbose_name_plural': 'error events',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status', '-last_seen'], name='diagnostics_status_8abcbe_idx'), models.Index(fields=['code', '-last_seen'], name='diagnostics_code_3f91b9_idx')],
            },
        ),
    ]
