# Generated by Django 6.0.8 on 2026-08-18 08:35

import core.storage
import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0023_meetingroom_audience_meetingroom_calendar_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSessionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_record', models.BooleanField(default=True, help_text='Start recording automatically when the host joins a session.')),
                ('publish_recordings', models.BooleanField(default=True, help_text='Publish finished recordings as past sessions students can re-watch.')),
                ('onedrive_root', models.CharField(default='Thrive Sessions', help_text='Top folder in the organiser’s OneDrive. Sessions are filed under <root>/<institution>/<programme>/<module>/<date + title>/.', max_length=120)),
                ('onedrive_owner_upn', models.CharField(blank=True, help_text='UPN whose OneDrive holds the whole tree. Blank = each session is filed in its own organiser’s drive.', max_length=255)),
                ('keep_teams_copy', models.BooleanField(default=False, help_text='Leave the original recording where Teams put it as well as filing a copy. Off = the recording is moved, so there is one copy, in one place.')),
                ('youtube_enabled', models.BooleanField(default=False, help_text='Upload finished recordings to YouTube and stream them in the platform. Needs YOUTUBE_* credentials in the environment.')),
                ('youtube_privacy', models.CharField(choices=[('unlisted', 'Unlisted'), ('private', 'Private'), ('public', 'Public')], default='unlisted', max_length=8)),
                ('youtube_daily_quota', models.PositiveIntegerField(default=10000, help_text='Your project’s daily YouTube Data API quota. An upload costs 1600 units, so the default cap allows about six a day before uploads must wait.')),
                ('thumbnail_background', models.ImageField(blank=True, help_text='Background image the session details are drawn on top of. Blank = a plain brand-coloured panel. Best at 1280×720.', null=True, storage=core.storage.files_storage, upload_to='sessions/backgrounds/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif']), core.validators.MaxFileSize(5)])),
                ('thumbnail_text_colour', models.CharField(default='#FFFFFF', max_length=9)),
                ('thumbnail_accent_colour', models.CharField(default='#C9A84C', max_length=9)),
                ('reminder_leads', models.CharField(default='1440,30', help_text='Minutes before a session to remind people, comma-separated. Default 1440,30 = 24 hours and 30 minutes.', max_length=100)),
                ('reminder_email', models.BooleanField(default=True, help_text='Also send reminders by e-mail.')),
                ('ai_followup_enabled', models.BooleanField(default=True, help_text='After each session, have the Claude admin layer write the full summary, the next session’s agenda and the action items. Runs as a background job on the admin account only.')),
                ('create_calendar_events', models.BooleanField(default=True, help_text='Also create a real Outlook/Teams calendar event for the organiser and any staff invitees. Needs the Calendars.ReadWrite application permission.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live session settings',
                'verbose_name_plural': 'Live session settings',
            },
        ),
        migrations.CreateModel(
            name='SessionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('waiting', 'Waiting for the session to end'), ('polling', 'Waiting for Teams artifacts'), ('filing', 'Filing to OneDrive'), ('summarising', 'Summarising'), ('uploading', 'Uploading to YouTube'), ('published', 'Published'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='waiting', max_length=12)),
                ('folder_id', models.CharField(blank=True, max_length=255)),
                ('folder_path', models.CharField(blank=True, help_text='Human-readable path of the session folder.', max_length=500)),
                ('folder_web_url', models.URLField(blank=True, max_length=1000)),
                ('drive_owner_upn', models.CharField(blank=True, max_length=255)),
                ('recording_item_id', models.CharField(blank=True, max_length=255)),
                ('recording_web_url', models.URLField(blank=True, max_length=1000)),
                ('recording_share_url', models.URLField(blank=True, help_text='Anonymous view link, for students who are not in the tenant.', max_length=1000)),
                ('recording_bytes', models.BigIntegerField(default=0)),
                ('recording_filed_at', models.DateTimeField(blank=True, null=True)),
                ('transcript_item_id', models.CharField(blank=True, max_length=255)),
                ('transcript_web_url', models.URLField(blank=True, max_length=1000)),
                ('summary_item_id', models.CharField(blank=True, max_length=255)),
                ('summary_web_url', models.URLField(blank=True, max_length=1000)),
                ('thumbnail_item_id', models.CharField(blank=True, max_length=255)),
                ('youtube_video_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('youtube_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_error', models.CharField(blank=True, max_length=300)),
                ('ai_followup_done', models.BooleanField(default=False)),
                ('ai_report_id', models.PositiveIntegerField(blank=True, help_text='The ai_assistant.AiReport holding the full write-up.', null=True)),
                ('announced_at', models.DateTimeField(blank=True, help_text='When the audience was told the recording is up. Stops a second announcement when the YouTube id lands after the OneDrive link.', null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='communication.meetingroom')),
            ],
            options={
                'verbose_name': 'Session artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_minutes', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('emailed', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_sent', to='communication.meetingroom')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['meeting', 'lead_minutes'], name='livesess_rem_meet_lead')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'recipient', 'lead_minutes'), name='uniq_session_reminder_per_lead')],
            },
        ),
    ]
