# Generated by Django 6.0.8 on 2026-08-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_usersettings_timezone'),
        ('communication', '0023_meetingroom_audience_meetingroom_calendar_event_and_more'),
        ('livesessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionartifact',
            name='unresolved_attendees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TeamsIdentityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(db_index=True, max_length=255, unique=True)),
                ('raw', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Resolved by a person'), ('inferred', 'Matched automatically')], default='manual', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_aliases', to='accounts.person')),
            ],
            options={
                'verbose_name': 'Teams identity alias',
                'verbose_name_plural': 'Teams identity aliases',
                'ordering': ['identity'],
            },
        ),
        migrations.CreateModel(
            name='SessionJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='The name we asked them to enter in Teams.', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_clicked_at', models.DateTimeField(auto_now_add=True)),
                ('last_clicked_at', models.DateTimeField(auto_now=True)),
                ('click_count', models.PositiveIntegerField(default=1)),
                ('matched_identity', models.CharField(blank=True, max_length=255)),
                ('matched_seconds', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='communication.meetingroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_joins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session join',
                'ordering': ['meeting', 'display_name'],
                'indexes': [models.Index(fields=['meeting', 'user'], name='livesess_join_meet_user')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'user'), name='uniq_session_join_per_user')],
            },
        ),
    ]
