# Generated by Django 6.0.8 on 2026-08-18 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesessions', '0002_sessionartifact_unresolved_attendees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What to call it on your calendar.', max_length=120)),
                ('url', models.URLField(help_text='The private iCalendar (.ics) address from your calendar app.', max_length=1000)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft 365 / Outlook'), ('apple', 'Apple iCloud'), ('other', 'Other (any .ics feed)')], default='other', max_length=10)),
                ('colour', models.CharField(default='#8E8E93', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('blocks_time', models.BooleanField(default=True, help_text='Count these events as busy when someone looks for a free slot to book.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('pending', 'Not synced yet'), ('ok', 'Syncing'), ('failed', 'Failing')], default='pending', max_length=8)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar subscription',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('busy', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='livesessions.calendarsubscription')),
            ],
            options={
                'verbose_name': 'Imported calendar event',
                'ordering': ['start'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='uniq_calendar_feed_per_user'),
        ),
        migrations.AddIndex(
            model_name='externalevent',
            index=models.Index(fields=['subscription', 'start'], name='livesess_ext_sub_start'),
        ),
    ]
