# Generated by Django 6.0.8 on 2026-08-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_modulephase_cohort'),
        ('livesessions', '0003_calendarsubscription_externalevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('show_past_sessions', models.BooleanField(default=True)),
                ('show_my_programme', models.BooleanField(default=True)),
                ('show_schedule', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_playlists', to='learning.cohort')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_playlists', to='learning.institution')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_playlists', to='learning.programme')),
                ('programme_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_playlists', to='learning.programmemodule')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_videos', to='learning.lesson')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='livesessions.youtubeplaylist')),
            ],
            options={
                'ordering': ['position', '-published_at'],
                'indexes': [models.Index(fields=['playlist', 'position'], name='livesession_playlis_de5f7d_idx')],
            },
        ),
    ]
