# Generated by Django 6.0.9 on 2026-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesessions', '0004_youtubeplaylist_youtubevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesessionsettings',
            name='onedrive_root',
            field=models.CharField(default='UCS Sessions', help_text='Top folder in the organiser’s OneDrive. Sessions are filed under <root>/<institution>/<programme>/<module>/<date + title>/.', max_length=120),
        ),
    ]
