# Generated by Django 6.0.6 on 2026-07-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='component',
            field=models.CharField(blank=True, choices=[('assignments', 'Assignments'), ('quizzes', 'Quizzes'), ('tests', 'Tests'), ('exams', 'Exams')], help_text='Report-card bucket this feeds. Blank = auto from the kind.', max_length=12),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Test'), ('exam_section', 'Exam section'), ('assignment', 'Assignment')], db_index=True, default='quiz', max_length=12),
        ),
    ]
