# Generated by Django 6.0.6 on 2026-07-02 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_component_alter_assessment_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='guidance',
            field=models.TextField(blank=True, help_text='Rubric / model answer shown to the marker (manual marking).'),
        ),
        migrations.AddField(
            model_name='question',
            name='marking_mode',
            field=models.CharField(choices=[('auto', 'Auto-marked (per-question key)'), ('manual', 'Manual marking (educator)')], default='auto', max_length=8),
        ),
    ]
