# Generated by Django 6.0.7 on 2026-07-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_answer_feedback_answer_marked_answer_marked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='proctor_action',
            field=models.CharField(choices=[('warn', 'Keep warning the student'), ('flag', 'Flag the attempt for the educator'), ('autosubmit', 'End the attempt and submit it')], default='flag', max_length=12),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctor_block_copy',
            field=models.BooleanField(default=True, help_text='Block copy, paste, right-click and printing during the attempt.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctor_blur_content',
            field=models.BooleanField(default=True, help_text='Hide the questions while the window is not focused.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctor_grace_seconds',
            field=models.PositiveSmallIntegerField(default=3, help_text='Seconds the pointer may sit outside the window before it counts.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctor_require_fullscreen',
            field=models.BooleanField(default=False, help_text='Ask for fullscreen and count leaving it as a warning.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctor_warn_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='Warnings allowed before the action below is taken. 0 = warn forever.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctoring_enabled',
            field=models.BooleanField(default=False, help_text='Watch for the student leaving the assessment window.'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='away_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='focus_warnings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='integrity_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='integrity_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('blur', 'Left the window (another app or window)'), ('hidden', 'Switched tab or minimised'), ('pointer_out', 'Pointer left the assessment window'), ('fullscreen', 'Left fullscreen'), ('copy', 'Tried to copy'), ('paste', 'Tried to paste'), ('contextmenu', 'Opened the right-click menu'), ('print', 'Tried to print')], default='blur', max_length=14)),
                ('counted', models.BooleanField(default=True, help_text='Whether this incremented the warning tally.')),
                ('seconds_away', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='assessments.assessmentattempt')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['attempt', 'created_at'], name='assessments_attempt_cba9f2_idx')],
            },
        ),
    ]
