# Generated by Django 6.0.7 on 2026-07-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_proctor_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10),
        ),
    ]
