# Generated by Django 6.0.8 on 2026-08-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Test'), ('mock_exam', 'Mock exam / past paper'), ('exam_section', 'Exam section'), ('assignment', 'Assignment')], db_index=True, default='quiz', max_length=12),
        ),
    ]
