# Generated by Django 6.0.8 on 2026-08-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_accountarchive_archive_dir_and_more'),
        ('assessments', '0008_alter_assessment_kind'),
        ('learning', '0021_programmemodule_chat_group_modulephase_moduleweek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='release_solution',
            field=models.CharField(choices=[('on_submit', 'As soon as the candidate submits'), ('on_close', 'When the paper closes'), ('manual', 'Only when a coach releases it')], default='on_submit', max_length=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='solution_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Stable key from the content pack that created this.', max_length=120),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.topic'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple choice'), ('multi', 'Multiple select'), ('tf', 'True / False'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('fill', 'Fill in the blank'), ('short', 'Short answer'), ('long', 'Long answer'), ('essay', 'Essay'), ('schedule', 'Numeric schedule'), ('image_select', 'Image selection'), ('diagram', 'Diagram labeling'), ('audio_resp', 'Audio response'), ('video_resp', 'Video response'), ('file_upload', 'File upload'), ('project', 'Project submission'), ('coding', 'Coding exercise')], default='mcq', max_length=14),
        ),
    ]
