# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_content_pack_fields'),
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='exam',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='learning.programmemodule'),
        ),
    ]
