# Generated by Django 6.0.8 on 2026-08-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_remove_assessment_subject_remove_exam_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='unit',
        ),
    ]
