# Generated by Django 6.0.8 on 2026-08-17 15:15

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_remove_assessment_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='answers/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='questions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif', 'mp3', 'wav', 'm4a', 'ogg', 'mp4', 'webm', 'mov', 'm4v']), core.validators.MaxFileSize(100)]),
        ),
    ]
