# Generated by Django 6.0.9 on 2026-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_alter_answer_file_alter_assignmentsubmission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='release_solution',
            field=models.CharField(choices=[('on_submit', 'As soon as the candidate submits'), ('on_close', 'When the paper closes'), ('manual', 'Only when a teacher releases it')], default='on_submit', max_length=10),
        ),
    ]
