# Generated by Django 6.0.9 on 2026-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_ucs_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Class / controlled test'), ('mock_exam', 'Practice exam / past paper'), ('exam_section', 'Examination paper'), ('assignment', 'Assignment')], db_index=True, default='quiz', max_length=12),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='release_solution',
            field=models.CharField(choices=[('on_submit', 'As soon as the learner submits'), ('on_close', 'When the paper closes'), ('manual', 'Only when a teacher releases it')], default='on_submit', max_length=10),
        ),
    ]
