"""UCS stories, imported from the school website's Info Hub.

Source: https://www.ucs.org.za/info-hub/ (pages 1 and 2), fetched 2026-10-08.
Each story keeps the original title, date, author, category and body text.
Body paragraphs are plain strings; a paragraph starting with "## " is a
sub-heading and one starting with "• " is a list item. Featured images
are stored as static files under static/images/stories/<slug>.jpg (resized
to max 1600px). Text is not HTML-escaped; Django templates autoescape it.
"""
import datetime

STORIES = [
    {
        'slug': 'leadership-2025',
        'title': '2025 LRC Heads',
        'date': datetime.date(2024, 9, 30),
        'author': 'Bongani Matlebe',
        'category': 'School Leadership',
        'categories': ['School Leadership'],
        'image': 'images/stories/leadership-2025.jpg',
        'image_width': 960,
        'image_height': 1280,
        'source_url': 'https://www.ucs.org.za/2024/09/30/leadership-2025/',
        'summary': 'Congratulations to our new LRC heads for 2025. UCS is delighted to have their support for the year ahead and we wish them every success in their leadership tenure. The team from left to right is…',
        'body': [
            'Congratulations to our new LRC heads for 2025. UCS is delighted to have their support for the year ahead and we wish them every success in their leadership tenure.',
            'The team from left to right is:',
            'Diyoka Kalombo (Senior LRC), Darin Wiafe (Senior LRC); Osinachi Okoro (Headgirl 2018), Valerie Malengele (Deputy Head Girl 2018)',
        ],
    },
    {
        'slug': 'success-ucs-lifted-belongs',
        'title': 'Success at UCS: Lifted up to where he belongs',
        'date': datetime.date(2018, 1, 19),
        'author': 'Colleen Lewis',
        'category': 'Great Results',
        'categories': ['Great Results'],
        'image': 'images/stories/success-ucs-lifted-belongs.jpg',
        'image_width': 1600,
        'image_height': 1067,
        'source_url': 'https://www.ucs.org.za/2018/01/19/success-ucs-lifted-belongs/',
        'summary': 'For former UCS learner, Bongani Matlebe, his biggest accomplishment to date has been to achieve one particular goal: to be at the very school he came from. “I was a beneficiary of the fundraising…',
        'body': [
            'For former UCS learner, Bongani Matlebe, his biggest accomplishment to date has been to achieve one particular goal: to be at the very school he came from. “I was a beneficiary of the fundraising programme that I am now managing as the newly appointed fundraiser at the school,” he explains. “This was a goal for me and is my greatest achievement so far.”',
            'Because when Bongani was a learner and beneficiary at UCS he always intended to give back to the school and the community. “I cannot think of a better way than what I am doing now,” he states.',
            'Bongani was born in the small mining town of Welkom, in the Free State. At the tender age of nine his dad passed away leaving him and his mom to fend for themselves. As the only provider left in the family, Bongani’s mother had to leave Welkom to seek work in Johannesburg. The pair ended up living in the tough inner-city neighbourhood of Berea and it was there that a close friend suggested Bongani apply to go to UCS. “The school already had an excellent reputation back then,” he says.',
            'He enrolled at UCS Primary school where he was a diligent student and did well. But then three years later things took a horrible turn when Bongani’s mom lost her job. She struggled to pay the rent so they had to move into a small space with a friend and she could no longer afford the school fees.',
            'When UCS principal Helenne Ulster became aware of the small family’s plight, she stepped in with the school’s Adopt a Child programme which assists learners who cannot afford to pay their school fees.',
            '“Adopt a Child saved my life. It quite literally kept me in school and off the streets where drugs and other such vices were very tempting for idle teenagers,” Bongani says.',
            'In high school he immersed himself in the arts. He participated in the choir and tap dancing. “Out of school hours, my tap teacher ran the Tap Talk Rhythm Company. Through the dance company I ended up touring the country and performing on many stages at the age of 14 and 15,” he says.',
            '“It was a positive escape and took me away from the seedy side of inner-city life. It opened my eyes to a better life. But even more than that it opened me up to my own potential. That’s just priceless.”',
            'Bongani was an ambitious learner and high achiever. He became a leader in Grade 12 but one of his biggest stand-out moments at UCS was when he represented the school in the ABSA and Rotary Club of Sandton Speech Competitions. He competed against learners from some of the most affluent schools in Johannesburg and reached the finals even though UCS did not have public speaking as an extra mural like many of the other schools did.',
            '“It was one of my proudest and most inspirational moments – it proved that the only difference between a UCS leaner and a leaner from St Stithians, for example, is access to opportunity and resources,” he says. “Our school did not have the resources, but I gave them all a run for their money.”',
            'Bongani matriculated in 2005 after which he became a teacher’s assistant at UCS and even had a helping hand in raising funds back then. He also continued to hone his performing arts skills and a year after matriculating he co-wrote a production for UCS called How Great Thou Arts, which was staged at the Wits Theatre.',
            'His subsequent years of working in the corporate sector and in the media industry saw him rising through the ranks from media planner to managing director. “My professional success is a tribute to the remarkable education offered by this life-changing institution,” he says.',
            'During all this time Bongani kept up his relationship with the school, such as assisting as the spiritual guidance facilitator for a time. In 2017 he achieved an ultimate goal when he was appointed as a director on the school board and took on the roles of fundraiser and marketing manager at UCS.',
            'Looking at Bongani’s steady rise to success, it is easy to attribute it to his go-getting spirit developed from the culture of success which runs through UCS.',
            '“The commitment of the principal, Helenne Ulster, and good old-fashioned discipline is what keeps this a quality school. It may sound simplistic, but in a generation that is rebellious with hardly any appreciation for the responsibilities that their freedoms come with, discipline has never been more critical. Just look at how it kept me off the city streets and provided me with an excellent education,” Bongani concludes.',
        ],
    },
    {
        'slug': 'leadership-at-ucs',
        'title': 'Leadership at UCS',
        'date': datetime.date(2018, 1, 8),
        'author': 'Colleen Lewis',
        'category': 'Great Results',
        'categories': ['Great Results'],
        'image': 'images/stories/leadership-at-ucs.jpg',
        'image_width': 1600,
        'image_height': 1200,
        'source_url': 'https://www.ucs.org.za/2018/01/08/leadership-at-ucs/',
        'summary': '“A leader is like a shepherd. He stays behind the flock, letting the most nimble go out ahead, whereupon the others follow, not realising that all along they are being directed from behind.” – Nelson…',
        'body': [
            '## Building Tomorrow’s Movers And Shakers At UCS',
            '“A leader is like a shepherd. He stays behind the flock, letting the most nimble go out ahead, whereupon the others follow, not realising that all along they are being directed from behind.” – Nelson Mandela.',
            'This quote from one of South Africa’s greatest leaders of all time will remain in their memories and hopefully inspires UCS’s 2017 LRCs (leaders) as they move to their next journey in life. And it’s all thanks to an important workshop which the newly voted LRCs must attend at the beginning of every new school year at UCS.',
            'The LRC Leadership Workshop is designed to inspire the school’s LRCs as developing leaders. UCS takes leadership very seriously. In fact, it plays into a fundamental part of the culture of success at the school.',
            'This year the workshop was hosted at the iconic Lilies Leaf Farm in January because who better than to learn from and be inspired by than South Africa’s liberation leaders. The UCS LRCs took a journey through the farm’s meaningful history and in so doing learnt about their own leadership abilities; what it takes to be a real leader.',
            'At most schools in South Africa leadership is encouraged and learners clamour for the prestigious role. The Department of Education believes the development of learner leaders in schools forms an integral part of shaping the future of the tomorrow’s leaders. For learners to be chosen as leaders they must exemplify and embody qualities and virtues of leadership such as:',
            '• Diligence',
            '• Accountability',
            '• Reliability',
            '• Good manners and respect',
            '• Team player',
            '• Willingness and enthusiasm',
            'There are some incredible benefits gained from children competing to become leaders at their schools. Here are the 5 most important reasons why leadership should be encouraged in our young people:',
            '• Gives learners a voice – When there are student leaders, it provides a sense of safety and confidence to the other learners because they have a group who will represent them.',
            '• Encourages community service – This is essential in South Africa where community service is a necessity and children should learn from an early age to give to the various communities in need. Community service promotes a sense of goodwill and builds a culture of awareness and caring.',
            '• Creates dedicated, committed, responsible and hard-working learners – To become a leader, learners must embody a good attitude. They must earn the respect of their fellow students and the staff at the school. They also need to have the best interests of the school at heart. This makes them worthy role models and citizens.',
            '• Builds confidence and self-esteem – The achievement of becoming a leader builds self-esteem. When learners are voted into leadership roles at school this tells them they are liked and trusted by their peers and their teachers. This builds confidence. To represent the school and become the responsible voice of the students at the school takes a lot of confidence.',
            '• Builds a good reputation – Universities and future employers take note of past achievements such as leadership roles. They form an opinion about the person they are interviewing based on their success at school.',
        ],
    },
    {
        'slug': 'responsibility-begins-school-ends-learner',
        'title': 'Responsibility Begins With The School And Ends With The Learner',
        'date': datetime.date(2017, 12, 14),
        'author': 'Colleen Lewis',
        'category': 'Activities',
        'categories': ['Activities'],
        'image': 'images/stories/responsibility-begins-school-ends-learner.jpg',
        'image_width': 1078,
        'image_height': 659,
        'source_url': 'https://www.ucs.org.za/2017/12/14/responsibility-begins-school-ends-learner/',
        'summary': 'It’s the school’s duty to teach children how to be responsible citizens! Take UCS, situated in the heart of Yeoville, in inner-city Johannesburg. This primary and high school epitomises the word…',
        'body': [
            'It’s the school’s duty to teach children how to be responsible citizens! Take UCS, situated in the heart of Yeoville, in inner-city Johannesburg. This primary and high school epitomises the word “responsibility”, which could be why it is a place of learning to be reckoned with. It stands out proudly in its community, a beacon of hope where young minds can learn in a safe environment without distractions.',
            'Owning a culture of responsibility begins with the school itself. UCS is a longstanding member of ISASA (Independent Schools Association of South Africa) which automatically accredits the school with the IQAA (Independent Quality Assurance Agency). Recently, UCS received two quality assurance inspections by Umalusi (Council for Quality Assurance in General and Further Education and Training) and it met the standards. In fact, it exceeded many. “Umalusi represents the government and IQAA represents ISASA. Both are designed to ensure that independent schools are run according to a particular standard of quality,” says UCS principal Helenne Ulster.',
            'To instil a sense of responsibility in the UCS learners, the school organises days when the children clean up their school as well as their community. “These kids live in a rough neighbourhood. There are no bins which means plenty of litter in the streets and on the sidewalks. They also get very little encouragement from home regarding the importance of keeping their environment clean,” Helenne says.',
            'Yet, when the learners are asked to spend a day cleaning up their inner-city community, they feel a sense of pride doing it. It gives them a sense of belonging and of empowerment being able to take control of the litter problem while making their neighbourhood look good.',
            'One of the most anticipated events at the school is Principal’s Day when Helenne hosts a workshop for the matric students and successful ex-learners give motivational talks. The aim of the workshop is to prepare the matrics for the challenges that lie ahead, once they leave the safety net of UCS. In large part, Helenne and her guest speakers promote accountability and responsibility because they form a fundamental part of the way in which the learners conduct themselves in the adult world.',
            'Finally, UCS is responsible for the wellbeing of some 500 primary and high school learners. This is one of the main reasons the school is participating in a Safety and Security initiative developed by Sacred Heart school with full participation from the JDA (Johannesburg Development Agency). “We want our children to feel safe and nurtured in the school environment as well as when they step outside our gates because educating them to become successful people means ensuring their welfare is taken care of holistically,” Helenne explains.',
            'Once children learn to become responsible by learning from responsible adults they soon gain two of the most vital things to help them become confident human beings: self-respect and respect for others. These are qualities UCS sees in its learners each and every day as they begin to embrace the culture of responsibility at the school.',
        ],
    },
    {
        'slug': 'school-makes-dreams-come-true',
        'title': 'A School That Makes Dreams Come True',
        'date': datetime.date(2017, 12, 13),
        'author': 'Colleen Lewis',
        'category': 'Great Results',
        'categories': ['Great Results'],
        'image': 'images/stories/school-makes-dreams-come-true.jpg',
        'image_width': 703,
        'image_height': 537,
        'source_url': 'https://www.ucs.org.za/2017/12/13/school-makes-dreams-come-true/',
        'summary': 'Melissa Thandokazi Sontashe was already dreaming of big business when she was little. Even though she was poor she would picture herself all grown up with lots of money. She pictured herself giving…',
        'body': [
            'Melissa Thandokazi Sontashe was already dreaming of big business when she was little. Even though she was poor she would picture herself all grown up with lots of money. She pictured herself giving some of that money to the less fortunate people who lived in her rural community.',
            '“From a young age I looked up to people like Oprah Winfrey.”',
            'As a girl she would sit in her grandmother’s small house in the Eastern Cape and imagine herself living this life. “My granny was very strict. As a child I didn’t like living with her because I was a very playful child and she would always reprimand me,” Melissa says.',
            'Her mother, who worked in Jo’burg as a cleaner at UCS, would visit during school holidays. “These were the best times ever because she’d bring us groceries and I’d get new clothes,” she says.',
            'Then in 2002 her grandmother passed away and she packed her meagre belongings to go back to Jo’burg with her mom. She was immediately enrolled at UCS. “I was fortunate enough to attend the school, which has a long-established reputation for providing an excellent standard of education. As a learner there I was recognised for my good academic performance.”',
            'After matriculating in 2013 Melissa went on to get a certificate in bookkeeping at Boston College, which was funded by UCS. The school recognised in her that spark of ambition and a desire to succeed. She proved her metal and was invited to become an intern at UCS in 2014.',
            '“I was given the opportunity to gain work experience and develop my skills at the school. This opportunity couldn’t have come at a better time because I was at a point where I was confused about the direction to take in my life. It didn’t help that my mother couldn’t afford the college fees on her salary and I was that close to becoming a dropout,” she says.',
            'Melissa began to intern in the UCS administration department assisting with learner account queries, capturing data, assisting in administering new applications and doing other office administration duties.',
            'She is currently doing her degree in Financial Accounting with UNISA, which is also being funded by the school. “I am very grateful for the opportunities I have been given by the school to realise my potential,” Melissa states.',
            'Now she is getting closer to her childhood dream. She is working hard to qualify as a chartered accountant so that one day she can run her own accountancy firm. “Being taken into the UCS family from the beginning of my school life and being able to study with a bursary has made my life so much easier,” she says.',
            '“When I was at my valedictory service in my last year of school and I was listening to all the words spoken and memories shared, I realised how my whole life has been in UCS. Everything I know today is because of every single person in the school who made an effort in building me up.”',
        ],
    },
    {
        'slug': 'nasa-astronaut-inspires-maths-learners',
        'title': 'NASA Astronaut Inspires Maths Learners',
        'date': datetime.date(2017, 11, 6),
        'author': 'Colleen Lewis',
        'category': 'Uncategorized',
        'categories': ['Uncategorized'],
        'image': 'images/stories/nasa-astronaut-inspires-maths-learners.jpg',
        'image_width': 666,
        'image_height': 374,
        'source_url': 'https://www.ucs.org.za/2017/11/06/nasa-astronaut-inspires-maths-learners/',
        'summary': 'Living Maths has seen numerous UCS learners achieve great results in Maths and Science. It also recently provided the opportunity for them to be inspired about reaching greatness. For several years…',
        'body': [
            'Living Maths has seen numerous UCS learners achieve great results in Maths and Science. It also recently provided the opportunity for them to be inspired about reaching greatness.',
            'For several years, UCS has nurtured a resourceful relationship with Living Maths, a programme that has provided mathematics support to thousands of learners around South Africa for over two decades.',
            'Because of this relationship, UCS has been able to support the development of many learners from the community in the areas of maths and science. And it’s thanks to the programme’s unique approach – through games, mysteries, brainteasers, fun activities, workshops and Olympiads – which helps learners from all walks of life to develop their maths skills.',
            'On 6th November, Living Maths had the great privilege of hosting American engineer and former NASA astronaut Dr Don Thomas at UCS.',
            '“As a pioneering school for the Living Maths programme in Gauteng, we were selected as the first school of choice to host Dr Thomas,” says UCS principal, Helenne Ulster. “The excitement was tangible and the learners were inspired by his presentation.”',
            'Dr Thomas’ talk opened the minds of the learners to a world where endless potential and possibility exists for them through maths and science.',
            '“UCS has always been passionate about and remains highly committed to giving our learners as much opportunity as we can by becoming proficient in Maths and Science,” says Ulster.',
            'As an independent school, which provides a quality education to disadvantaged children living in the Johannesburg inner-city, UCS keenly understands the scarcity of maths and science skills across South Africa’s various economic sectors. Ulster and her team of educators believe their goal is to enable as many of their learners as possible to enter the workplace at any level with skills grounded in maths and science.',
            '“This is why we are always delighted to have visitors who inspire our learners in their journey and Dr Thomas provided just that,” Ulster concludes.',
        ],
    },
    {
        'slug': 'ucs-learners-one-dedicated-parent-away-reaching-success',
        'title': 'UCS learners are one dedicated parent away from reaching success',
        'date': datetime.date(2017, 10, 6),
        'author': 'Colleen Lewis',
        'category': 'Uncategorized',
        'categories': ['Uncategorized'],
        'image': 'images/stories/ucs-learners-one-dedicated-parent-away-reaching-success.jpg',
        'image_width': 1280,
        'image_height': 960,
        'source_url': 'https://www.ucs.org.za/2017/10/06/ucs-learners-one-dedicated-parent-away-reaching-success/',
        'summary': 'Behind every UCS parent is a learner striving for a better future; one where a child can dream of becoming anything she puts her mind to. Mpuseng Dorah Mabusela, or Dorah (second from left) as she is…',
        'body': [
            'Behind every UCS parent is a learner striving for a better future; one where a child can dream of becoming anything she puts her mind to.',
            'Mpuseng Dorah Mabusela, or Dorah (second from left) as she is known to everyone at UCS (United Church School) where she works, is a hardworking single parent of three – a daughter and two sons.',
            'In the 1970s, Dorah was living in Pretoria struggling to make ends meet and so she moved to Johannesburg in search of a better life. “Growing up as a little girl my family and I had to do all that we could to survive,” she says.',
            'Her young life consisted of 4am wakeup calls to go fetch water and firewood so the family could cook and clean. She would do this every day before setting off for school. “By the time I got to school I was too exhausted to learn properly,” Dorah explains.',
            'She was eventually forced to drop out of school because of the poverty. She would often end up eating yesterday’s pap crusts as bread for breakfast. “Life was extremely hard and unimaginable. Christmas time was like heaven on earth because that’s when I got to eat bread, custard and jelly. If times were not as bad, I’d even get a new outfit. It was hard back then,” she says.',
            'When Dorah arrived in Johannesburg she worked the odd job but often found herself unemployed. Then in 2005, her luck turned around when an aunt let Dorah know of a vacancy at the school where she was working. She went for an interview and got the job. The school was UCS and Dorah has been employed there ever since. She is happy working at the school and takes pride in her job but the cherry on the top was that her daughter, Teboho, enrolled there as a learner and excelled to eventually become an intern teacher at UCS Primary school. This was even more poignant for Dorah because her sons never managed to get their grade 12s due to life’s harsh circumstances. “I knew that my daughter was going to be in good hands. The school is very disciplined. Good morals and values are instilled in the learners. The teachers are outstanding and go out of their way to make sure the learners get educated and get the best results. I am so proud of my daughter as an intern at the school. She too will become a great teacher one day soon,” says Dorah.',
            'Read Teboho’s story about life as an intern at UCS.',
            'Life is good but mom and daughter still had their fair share of challenges. Dorah had to find enough taxi fare for them both to get to UCS in the middle of Yeoville when they were living in Soweto. They were also waking up at 3 in the morning to make sure they got to school on time. Realising their struggles, UCS came to their rescue by providing them with accommodation close to the school. Dorah and Teboho have been living there for 6 years now. “I am truly blessed as a mother because thanks to the internship programme my daughter was educated to educate more learners to become the future leaders, doctors, engineers and business owners of our tomorrow,” Dorah concludes.',
        ],
    },
    {
        'slug': 'reaching-dreams-ucs',
        'title': 'Reaching For Her Dreams At Ucs',
        'date': datetime.date(2017, 9, 4),
        'author': 'Colleen Lewis',
        'category': 'Uncategorized',
        'categories': ['Uncategorized'],
        'image': 'images/stories/reaching-dreams-ucs.jpg',
        'image_width': 681,
        'image_height': 672,
        'source_url': 'https://www.ucs.org.za/2017/09/04/reaching-dreams-ucs/',
        'summary': 'Picture this: A little girl standing all alone in her small bedroom surrounded by an imaginary class of children. And she is the teacher. She uses scruffy old magazines as the text books. Teaching to…',
        'body': [
            'Picture this: A little girl standing all alone in her small bedroom surrounded by an imaginary class of children. And she is the teacher. She uses scruffy old magazines as the text books. Teaching to her imaginary class is her daily game. She is poor but loved dearly by her single mom and grandparents. She is raised with good morals and values. Her dream for teaching blossoms in that small bedroom. It grows as a passion in her imagination. One day she will become a real teacher.',
            'This small child is now a young woman. Her name is Tebogo Mabusela. She is 18-years old and recently started her teaching internship at UCS (United Church School) in Yeoville, Johannesburg. She matriculated at this school. Now she will become a fully qualified teacher there.',
            'It’s all thanks to the education she received at home and at UCS that is seeing her childhood dream become a reality. “I come from a strict family. They believe that education plays a fundamental role in our lives. My grandfather gives me motivational talks about life to make sure I stay on the right track. He often tells me if I have a goal to keep going no matter what to get to that goal. This motivates me. I knew from the get go what I wanted to do in life and I would find my way there no matter what,” says Tebogo.',
            'Her grandparents had a very positive impact on her life. They showed her what it meant to be loved and nurtured. “It gave me the love and passion I have for children. I want to help children. From the age of 12, I already knew about the poverty in our country and about orphaned children. I wanted to foster them and teach them,” she says.',
            'Being a learner at UCS worked out well for Tebogo because the school runs a successful teachers’ internship programme. It sponsors the tertiary fees at any South African university for UCS learners wanting to become teachers.',
            'The school also offers practical training and helps equip the interns to become brilliant teachers, who will then teach at UCS. The internship is designed to produce the best quality educators who will, in turn, produce excellent learners.',
            'But her journey to learning and becoming a teacher hasn’t always been an easy one. As her two older brothers never received a grade 12, there was immense pressure on Tebogo to succeed. “The final exam period was intense for me. I felt like I had not only my family but the whole community putting pressure on me to do well. People were telling me how hard life would be if I didn’t pass my matric. It was a bumpy ride. I had to be strong for myself to succeed. In the end, though I knew everyone was encouraging me to do my best,” Tebogo explains.',
            'She recalls times at UCS when she would participate in class assemblies by reciting speeches in front of teachers, learners and guests. This was an accomplishment for her as it helped boost her self-esteem and give her practice for the many, many times she would be standing in front of her learners one day as a teacher. “I was very active at school and I did not limit myself. I was chosen to be a Prefect in primary school and then to be part of the Learner Representative Council in high school. Even though I was quite an over-weight child in primary school I still took part in athletics and did long distance running. I became part of the volleyball team and with the good skills I had I was chosen as team captain,” she says. “At UCS we are taught to believe anything is possible.”',
            'With her zero-limit attitude and good home-grown values, Tebogo is sure to go far in life and teach other youngsters to reach for their dreams. And, with UCS’s support she has not only reached for her dreams to become a teacher, she has also secured a place in the future with that rare group of teachers who excel.',
        ],
    },
    {
        'slug': 'ucs-helped-learner-help-others',
        'title': 'How Ucs Helped A Learner To Help Others',
        'date': datetime.date(2017, 6, 15),
        'author': 'Colleen Lewis',
        'category': 'Great Results',
        'categories': ['Great Results'],
        'image': 'images/stories/ucs-helped-learner-help-others.jpg',
        'image_width': 540,
        'image_height': 540,
        'source_url': 'https://www.ucs.org.za/2017/06/15/ucs-helped-learner-help-others/',
        'summary': '25-year old Thabiso Chauke is a real go-getter. He is also a giver of gifts as the founder of Two Pairs of Shoes. The NGO puts school shoes on the feet of children who cannot afford to buy their own.…',
        'body': [
            '25-year old Thabiso Chauke is a real go-getter. He is also a giver of gifts as the founder of Two Pairs of Shoes. The NGO puts school shoes on the feet of children who cannot afford to buy their own. “I went to a very good school. So, I thought it was important for me to give back through the Two Pairs of Shoes foundation,” he says.',
            'And the “very good school” Chauke is talking about is UCS. He joined there as a high school learner in 2008 and matriculated in 2010. “If there is one opportunity in my life with which I have been blessed it was to be part of the winning team that is United Church School,” he remarks. “The love, care and compassion of the teachers at the school comes naturally. It is part of the school’s culture.”',
            'While love and nurturing played an extremely important role in Chauke’s school career, it was UCS’s ability to turn the young man into a leader and public speaker that were responsible for him finding success in life. “I developed an interest in politics because of some of the history teachers at United Church School,” Chauke states.',
            'What impressed the diligent high school learner was the way UCS embraced the African continent as a whole, welcoming learners from the various countries in Africa to benefit from a great school experience at UCS. “The teachers helped transform me into a confident, achieving young man. As I continue to serve in the public sector I will forever embrace the discipline of education instilled in me by UCS,” says Chauke. “I will continue to help empower other young minds just as I was empowered by United Church School over the years.”',
            'Chauke didn’t only meet President Zuma, he is also currently working with important government spokespeople, including Mthunzi Mhaga of the Department of Justice and Correctional Services, who has joined hands with Two Pairs of Shoes to get needy students geared up for school.',
        ],
    },
    {
        'slug': 'helping-reunite-learner-father',
        'title': 'Helping Reunite A Learner With His Father',
        'date': datetime.date(2017, 6, 15),
        'author': 'Colleen Lewis',
        'category': 'Uncategorized',
        'categories': ['Uncategorized'],
        'image': 'images/stories/helping-reunite-learner-father.jpg',
        'image_width': 1024,
        'image_height': 683,
        'source_url': 'https://www.ucs.org.za/2017/06/15/helping-reunite-learner-father/',
        'summary': 'Perhaps it’s the experience she has gained from working at organisations like Nkosi’s Haven that gives UCS’s social worker Jane Mwase the innate ability to spot a troubled child and provide the right…',
        'body': [
            'Perhaps it’s the experience she has gained from working at organisations like Nkosi’s Haven that gives UCS’s social worker Jane Mwase the innate ability to spot a troubled child and provide the right kind of care.',
            'If it weren’t for this nurturing spirit, a Matric learner at the school would probably not have been reunited with his father. “He was having problems coping in his classes when I discovered, in a session with him, that he had never met his father. This was upsetting him and distracting him,” says Jane.',
            'Sadly, the learner’s mother was refusing to tell him where his father could be found. Jane decided the best solution would be to hold some sessions which included the boy’s family. Through sheer determination and lots of care, progress was made and Jane helped father and son reunite. “It was a heart-warming moment when we discovered the father had been looking for his boy and desperately wanted to meet him. To this day the learner still contacts me every time he goes to visit his father to tell me that he’s been to see him,” she remarks.',
            'It’s not only the academic achievements that make UCS a thriving inner-city school, it’s also the successes where learners have overcome social and emotional challenges that give it a compassionate reputation.',
        ],
    },
    {
        'slug': 'skills-development-physical-play-vital-academics',
        'title': 'Skills Development – Physical play is as vital as the academics',
        'date': datetime.date(2017, 5, 31),
        'author': 'Colleen Lewis',
        'category': 'Activities',
        'categories': ['Activities'],
        'image': 'images/stories/skills-development-physical-play-vital-academics.jpg',
        'image_width': 900,
        'image_height': 480,
        'source_url': 'https://www.ucs.org.za/2017/05/31/skills-development-physical-play-vital-academics/',
        'summary': 'UCS doesn’t let a challenge get in its way of providing the learners with a well-rounded education. In fact, the educators at the school have simply learned to think and work out of the box. One…',
        'body': [
            '## 5 ways skills development helps young children',
            'UCS doesn’t let a challenge get in its way of providing the learners with a well-rounded education. In fact, the educators at the school have simply learned to think and work out of the box. One example is how the school tackles skills development. With very little outdoor play space available on the school premises, deputy principal Louise Tamboer makes use of the public parks in the community for the school’s skills development programme for its young primary school learners.',
            '## Vital Development',
            'The children need to develop ball skills, cognitive skills, eye-hand co-ordination, gross-motor skills, and creative thinking as well as auditory, tactile, gustatory and olfactory perception. And the two community parks in the area make ideal settings for physical play while developing gross motor and ball skills in the outdoors.',
            '“Children love nothing more than playing in parks. So once we moved our skills development classes into the public parks, they became our most anticipated lessons of the week,” says Louise.',
            'Now, whether sunny or cold, the children and teachers make their way in an orderly fashion every Thursday morning to the various parks close to the school for a morning of outdoor fun.',
            '“We split the grades up. Grades 1 to 3 go to one park and 4 to 6 to another. The learners spend at least one-and-a-half hours kicking balls and improving their gross-motor skills on the playground equipment,” Louise explains.',
            '“Ideally our children should be doing this on a daily basis but we sadly lack the space and don’t have the funds for things like jungle gyms. It would be nice but play equipment is a luxury when we are caring for hundreds of children, most of whom come from disadvantaged backgrounds.”',
            'Fortunately, the school is able to encourage fine-motor skills in the classroom by including fun activities such as knitting, weaving and bead-threading. These skills also develop creativity in the children.',
            '## Skills development in the form of physical play is just as important to growing children as learning to read and write.',
            '## Here are 5 reasons why:',
            '• They learn to co-ordinate their movements which promotes confidence and encourages them to explore their environments.',
            '• They socialise which helps them connect and learn to operate appropriately in the world.',
            '• They keep fit and healthy which is fundamental to a child’s physical growth and development.',
            '• They learn to think creatively as they negotiate obstacles in their landscape and play imaginary games.',
            '• They have fun which is vital for children to maintain a good balance in life.',
            'At UCS emphasis is placed on holistic development by encouraging both personal and academic growth in all our learners. Find out about our programmes and facilities to see how we educate well-rounded children.',
        ],
    },
    {
        'slug': 'school-outings-enhance-learning',
        'title': 'School Outings Enhance Learning',
        'date': datetime.date(2017, 5, 29),
        'author': 'Colleen Lewis',
        'category': 'Knowledge',
        'categories': ['Knowledge'],
        'image': 'images/stories/school-outings-enhance-learning.jpg',
        'image_width': 900,
        'image_height': 480,
        'source_url': 'https://www.ucs.org.za/2017/05/29/school-outings-enhance-learning/',
        'summary': 'The Woolies Class Visits are something to look forward to at UCS. The primary school learners are filled with excitement as they countdown to the date of the visit. It’s a little like anticipating a…',
        'body': [
            '## 5 reasons why school excursions benefit children',
            'The Woolies Class Visits are something to look forward to at UCS. The primary school learners are filled with excitement as they countdown to the date of the visit. It’s a little like anticipating a birthday, or even Christmas.',
            'The reason for all the excitement is because the Woolies Class Visits take place only once a year. It’s also the only excursion the UCS primary school learners will go on in the space of a year. The school understands the importance of outings but lacks the budget for transport. It does the best it can with the money it has by sending the children on one worthwhile educational trip.',
            '## The Woolies Group',
            'The Woolworths Group sends a representative to the UCS Grade 4, 5 and 6 classes. “The lessons are derived from the syllabus for those grades. They are taught where food comes from, the manufacturing process and many other relevant topics for these grades,” explains Louise Tamboer, deputy principal at UCS.',
            'After the Woolworths representative has finished presenting a lesson to the various classes, the children then take a memorable trip behind the scenes of Woolworths’ stores. They visit various branches and distribution warehouses where they learn all about the journey food takes from factory and farm to shelf. They also learn all about food as a nutritional source. “They talk about The Woolies Class Visit for weeks after the outing and they learn so much from it,” says Louise.',
            'Children spend a lot of time in classrooms listening to their teachers and learning in the process. It’s therefore vital for their young minds to explore beyond the four walls and blackboard. School outings are purposefully placed in the curriculum for learners to benefit from the incredible interaction and engagement they receive when they leave the classrooms to learn something.',
            'The UCS high school also has an excursions programme where Grade 7s go to Sci Bono, Grade 8s to SABC, Grade 9s the Delta Environmental Centre, Grade 10s to the Pretoria Prison, Grade 11s to Gold Reef City, and Grade 12s get to enjoy a theatre visit based on their set work.',
            '## Here are 5 reasons why school excursions are so important for learners:',
            '• They reinforce – Excursions are an excellent and interesting way of reinforcing what is being taught in class. They help the children to better understand.',
            '• They encourage engagement – Teachers and learners can interact and engage more when out of their day-to-day environment. Trips can be turned into mobile classrooms and teachers can instruct learners to investigate topics differently to the norm and then quiz them when they are back in the classroom.',
            '• They build social skills – The children get to interact with their classmates, teachers and excursion representatives. They learn how to socialise and behave out of the school environment.',
            '• They provide exposure – The children get to visit places where they have never been before. This is a big plus for learners who are less fortunate and don’t have the opportunity to travel.',
            '• They help with retention – Educational trips create “episodic memories” which ultimately help children to retain information for much longer periods. In other words, excursions provide unforgettable moments so everything learnt on these special trips remain as good memories.',
            'The educators at UCS have experienced the benefits of school outings first hand and would like to increase the learner’s excursions to at least 3 a year. This would provide more variety for the children and help them learn and explore in exciting new environments. Ideally, the school requires more funds to finance the transport to and from excursions. Click here to find out what the budget looks like for 3 annual school outings.',
        ],
    },
    {
        'slug': 'literacy-education',
        'title': 'Stories Unite Us at UCS',
        'date': datetime.date(2017, 5, 21),
        'author': 'Colleen Lewis',
        'category': 'Uncategorized',
        'categories': ['Uncategorized'],
        'image': 'images/stories/literacy-education.jpg',
        'image_width': 950,
        'image_height': 630,
        'source_url': 'https://www.ucs.org.za/2017/05/21/literacy-education/',
        'summary': 'The educators at UCS all have a story to tell. One that ultimately benefits the learners at the school. Take Louise for example, who is head of UCS Primary School. She has taught at a variety of…',
        'body': [
            '## Behind every UCS educator is a story that speaks of experience. Deputy principal Louise Tamboer provides her literacy education expertise gained in Jamaica to teaching reading skills to Yeoville’s children.',
            'The educators at UCS all have a story to tell. One that ultimately benefits the learners at the school. Take Louise for example, who is head of UCS Primary School. She has taught at a variety of schools all around South Africa, as well as abroad. “I was in a very fortunate position to have taught in many schools across our country due to my marriage to a Minister of Religion in our church,” says Louise.',
            'She has taught children in small farm schools, mission station schools, tough township schools and even a school in Jamaica, where Louise had the privilege of teaching a remedial class. She believes the experience she gained there is helping primary school learners at UCS who are struggling with reading.',
            '“I am always ready for the challenge when teachers send me learners who struggle with reading, especially phonetics,” she says. “I readily tap into my 5 years of experience teaching my remedial learners in Jamaica. There I taught children who had to repeat a grade because they lacked reading skills. Thanks to my past experience, today I am better equipped to help our learners excel, especially in reading.”',
            'Louise takes her responsibilities as the head of UCS Primary School very seriously. “I must be an example to the teaching staff, the support staff and the cleaning staff. We all contribute to the smooth-running of UCS. It is very important that we have the entire school at heart.”',
        ],
    },
    {
        'slug': 'confidence-through-literacy',
        'title': 'Building Confidence Through Literacy',
        'date': datetime.date(2017, 5, 21),
        'author': 'Colleen Lewis',
        'category': 'Uncategorized',
        'categories': ['Uncategorized'],
        'image': 'images/stories/confidence-through-literacy.jpg',
        'image_width': 1280,
        'image_height': 768,
        'source_url': 'https://www.ucs.org.za/2017/05/21/confidence-through-literacy/',
        'summary': 'UCS teachers are passionate about building literacy at their primary school. The library at the school is a perfect example of how seriously books and reading feature in the children’s daily lives.…',
        'body': [
            '## When children learn to read, it improves their overall confidence and self-esteem.',
            'UCS teachers are passionate about building literacy at their primary school. The library at the school is a perfect example of how seriously books and reading feature in the children’s daily lives. It was created to accommodate books which were generously donated by a South African company. Most of the books were purchased at Exclusive Books for the UCS library. “We have also had quite a number of used books donated to us by individuals,” says Louise Tamboer, deputy principal of UCS Primary School.',
            'Now, the Foundation Phase learners go weekly to the library, one class at a time. “The Librarian, Ms Masola, reads a story to the class. The children then get to take a book home to return back to the library – in the same condition they found it – one week later,” Louise explains.',
            'The school takes a strict and disciplined approach to the library by teaching the children from a young age to respect and care for the books. However, the emphasis is still on fun. “We want our children to embrace reading,” says Louise. “There is nothing more affirming to me than seeing those little faces light up at story time.”',
            'Another important literacy activity for UCS is the City of Jo’burg Library and Information Services Story Skirmish, an inter-schools knock-out quizz. The UCS Grade 4 and 5 learners enter the competition. They are challenged to read the books and then answer questions verbally. UCS has participated in this competition since 2012 and has done extremely well by reaching the semi-finals on two occasions.',
        ],
    },
]

STORIES.sort(key=lambda s: s["date"], reverse=True)

_BY_SLUG = {s["slug"]: s for s in STORIES}


def all_stories():
    """Return every story, newest first."""
    return list(STORIES)


def recent(n=4):
    """Return the ``n`` most recent stories."""
    return STORIES[:n]


def get(slug):
    """Return the story with this slug, or None."""
    return _BY_SLUG.get(slug)
