# Generated by Django 6.0.6 on 2026-07-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0002_event_owner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_materials_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of required extra materials, if any', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='ZAR', max_length=8),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='What the student will achieve'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text='e.g. Beginner / Intermediate / Advanced', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='min_study_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum study hours per week', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='num_documents',
            field=models.PositiveIntegerField(blank=True, help_text='Documents included', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='num_tests',
            field=models.PositiveIntegerField(blank=True, help_text='Number of tests / assessments', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_mark',
            field=models.PositiveIntegerField(blank=True, help_text='Pass requirement (%)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, help_text='What is needed from the student to participate'),
        ),
        migrations.AddField(
            model_name='course',
            name='session_schedule',
            field=models.TextField(blank=True, help_text='Dates & times of the live sessions'),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, help_text='Short overview for cards / search results'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_get',
            field=models.TextField(blank=True, help_text='Access / deliverables the student receives'),
        ),
        migrations.AddField(
            model_name='course',
            name='whats_included',
            field=models.TextField(blank=True, help_text='What the course includes'),
        ),
        migrations.CreateModel(
            name='CourseAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('one_on_one', 'One-on-one session with educator'), ('special_attention', 'Special attention (extra support)'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='myhub.course')),
            ],
            options={
                'ordering': ['course', 'name'],
            },
        ),
    ]
