# Generated by Django 6.0.8 on 2026-08-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_person_department'),
        ('myhub', '0003_course_additional_materials_cost_and_more'),
        ('orgtasks', '0006_remove_task_department_alter_task_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
