# Generated by Django 6.0.8 on 2026-08-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0004_remove_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='The e-mail subject line.', max_length=255),
        ),
    ]
