# Generated by Django 6.0.8 on 2026-08-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_invitation_course_remove_person_child_student_and_more'),
        ('communication', '0020_remove_announcement_courses_remove_chatgroup_course_and_more'),
        ('learning', '0023_remove_courseitemprogress_item_and_more'),
        ('myhub', '0005_alter_emailtemplate_subject'),
        ('orgtasks', '0008_remove_task_course_task_programme_and_more'),
        ('reports', '0006_remove_certificate_course_alter_certificate_kind'),
        ('shop', '0006_remove_product_course_alter_product_educator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='courseaddon',
            name='course',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='LibraryItem',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseAddon',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
