# Generated by Django 6.0.6 on 2026-07-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='program',
        ),
    ]
