# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
        ('shop', '0004_remove_product_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subject',
        ),
        migrations.AddField(
            model_name='product',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_products', to='learning.programmemodule'),
        ),
    ]
