# Generated by Django 6.0.8 on 2026-08-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_invitation_course_remove_person_child_student_and_more'),
        ('shop', '0005_remove_product_subject_product_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course',
        ),
        migrations.AlterField(
            model_name='product',
            name='educator',
            field=models.ForeignKey(blank=True, help_text='The instructor for this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_products', to='accounts.person'),
        ),
    ]
