# Generated by Django 6.0.8 on 2026-08-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_alter_institution_logo_alter_lesson_author_avatar_and_more'),
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Blank = a general item everyone can see (merchandise, open resources).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='learning.institution'),
        ),
        migrations.AddField(
            model_name='product',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Narrows the item to one programme at that institution. Blank = all of them.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='learning.programme'),
        ),
    ]
