# Generated by Django 6.0.8 on 2026-08-18 05:22

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_institution_product_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='The zip or document the buyer downloads once the order is paid.', null=True, upload_to='shop/downloads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'rtf', 'odt', 'ods', 'odp']), core.validators.MaxFileSize(25)]),
        ),
    ]
