# Generated by Django 6.0.8 on 2026-08-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_alter_institution_logo_alter_lesson_author_avatar_and_more'),
        ('shop', '0009_product_digital_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Shown to the buyer, e.g. "Launch week – 20% off".', max_length=120)),
                ('code', models.CharField(blank=True, help_text='Leave blank for an automatic promotion; set it to require a coupon code.', max_length=32, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('amount', 'Fixed amount off')], default='percent', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0–100) or a rand amount, per discount_type.', max_digits=8)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, help_text='Cart total the discount needs before it applies.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='shop.productcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='learning.institution')),
                ('products', models.ManyToManyField(blank=True, help_text='Specific items. Blank = anything else in scope.', related_name='discounts', to='shop.product')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='learning.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
