# Generated by Django 6.0.8 on 2026-09-28 09:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_usersettings_calendar_token'),
        ('communication', '0024_feedattachment'),
        ('finance', '0008_bookings'),
        ('shop', '0011_commerce_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booking_window_days',
            field=models.PositiveSmallIntegerField(default=28, help_text='How far into the future sessions can be booked.'),
        ),
        migrations.AddField(
            model_name='product',
            name='buffer_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Gap kept free either side of every session.'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_notice_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='How far ahead a session must be booked.'),
        ),
        migrations.AddField(
            model_name='product',
            name='reschedule_cutoff_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='A student may move a session until this many hours before it.'),
        ),
        migrations.AddField(
            model_name='product',
            name='session_lengths',
            field=models.CharField(default='30,60,90,120', help_text='Minutes a student may book, comma-separated.', max_length=40),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('minutes', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('held', 'Held — awaiting payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='held', max_length=10)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reschedule_count', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, help_text='What the student would like to cover.')),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_taught', to='accounts.person')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='communication.meetingroom')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='shop.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='shop.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='shop.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='finance.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Credit entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducatorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.person')),
            ],
            options={
                'verbose_name_plural': 'Educator availability',
                'ordering': ['educator', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EducatorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rates', to='accounts.person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator_rates', to='shop.product')),
            ],
            options={
                'ordering': ['hourly_rate', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducatorTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='accounts.person')),
            ],
            options={
                'verbose_name_plural': 'Educator time off',
                'ordering': ['start'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['educator', 'start'], name='shop_bookin_educato_959d77_idx'),
        ),
        migrations.AddConstraint(
            model_name='educatorrate',
            constraint=models.UniqueConstraint(fields=('product', 'educator'), name='uniq_rate_per_educator_per_service'),
        ),
    ]
