# Generated by Django 6.0.8 on 2026-09-28 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_bookings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_label',
            field=models.CharField(blank=True, help_text='What the buyer chose, e.g. "Courier Guy Economy".', max_length=160),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('door', 'Door-to-door'), ('locker', 'Pudo locker')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_to',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=120, verbose_name='Recipient name')),
                ('phone', models.CharField(help_text='The courier SMSes delivery updates to this number.', max_length=30, verbose_name='Mobile number')),
                ('street_address', models.CharField(help_text='Street number and name.', max_length=200)),
                ('complex', models.CharField(blank=True, max_length=120, verbose_name='Unit / complex / building')),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal'), ('EC', 'Eastern Cape'), ('FS', 'Free State'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NW', 'North West'), ('NC', 'Northern Cape')], max_length=3)),
                ('postal_code', models.CharField(max_length=4)),
                ('address_type', models.CharField(choices=[('residential', 'Home'), ('business', 'Work / business')], default='residential', max_length=12)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('ready', 'Ready to pack'), ('booked', 'Courier booked'), ('in_transit', 'On its way'), ('delivered', 'Delivered'), ('failed', 'Delivery problem'), ('cancelled', 'Cancelled')], db_index=True, default='awaiting_payment', max_length=20)),
                ('method', models.CharField(choices=[('door', 'Door-to-door'), ('locker', 'Pudo locker')], max_length=10)),
                ('carrier', models.CharField(choices=[('courier_guy', 'The Courier Guy'), ('manual', 'Other / manual')], default='courier_guy', max_length=20)),
                ('service_level', models.CharField(blank=True, help_text='Courier service code, e.g. ECO.', max_length=40)),
                ('locker_code', models.CharField(blank=True, max_length=60)),
                ('locker_name', models.CharField(blank=True, max_length=200)),
                ('charged', models.DecimalField(decimal_places=2, default=0, help_text='What the buyer paid for delivery.', max_digits=10)),
                ('courier_cost', models.DecimalField(blank=True, decimal_places=2, help_text='What the courier charged us (from the booking).', max_digits=10, null=True)),
                ('tracking_reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('courier_shipment_id', models.CharField(blank=True, max_length=80)),
                ('courier_name', models.CharField(blank=True, help_text='For manual shipments.', max_length=80)),
                ('tracking_url', models.URLField(blank=True)),
                ('events', models.JSONField(blank=True, default=list, help_text='Tracking history, newest last.')),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='shop.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
