# Generated by Django 6.0.6 on 2026-07-03 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_mail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='feed/%Y/%m/')),
                ('media_kind', models.CharField(blank=True, max_length=10)),
                ('kind', models.CharField(default='text', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Everyone'), ('groups', 'My groups & classes'), ('staff', 'Staff & admins')], default='public', max_length=10)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='communication.chatgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
