# Generated by Django 6.0.6 on 2026-07-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_feed'),
        ('myhub', '0002_event_owner_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='program',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='group',
        ),
        migrations.AddField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='myhub.course'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='myhub.course'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='kind',
            field=models.CharField(choices=[('direct', 'Direct (1:1)'), ('course', 'Course group'), ('subject', 'Subject group'), ('custom', 'Custom group')], default='custom', max_length=10),
        ),
    ]
