# Generated by Django 6.0.6 on 2026-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_remove_chatgroup_group_remove_chatgroup_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone'), ('groups', 'My courses & subjects'), ('staff', 'Staff & admins')], default='public', max_length=10),
        ),
    ]
