# Generated by Django 6.0.6 on 2026-07-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_person_emergency_contact'),
        ('communication', '0009_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='artifacts_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='organizer_upn',
            field=models.CharField(blank=True, help_text='Microsoft UPN of the meeting organiser (the licensed educator).', max_length=255),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='provider',
            field=models.CharField(choices=[('teams', 'Microsoft Teams'), ('jitsi', 'Jitsi')], default='jitsi', max_length=10),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='teams_join_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='teams_meeting_id',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
