# Generated by Django 6.0.6 on 2026-07-16 03:11

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_meetingroom_artifacts_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionattachment',
            name='file',
            field=models.FileField(storage=core.storage.files_storage, upload_to='discussions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='media',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='feed/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=core.storage.files_storage, upload_to='chat/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='workspacefile',
            name='file',
            field=models.FileField(storage=core.storage.files_storage, upload_to='workspaces/%Y/%m/'),
        ),
    ]
