# Generated by Django 6.0.7 on 2026-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_alter_discussionattachment_file_alter_feed_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='seconds_attended',
            field=models.PositiveIntegerField(default=0, help_text='Seconds the student was actually present, from heartbeats.'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='finalised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='min_attendance_pct',
            field=models.PositiveIntegerField(default=50, help_text='Share of the session a student must actually attend to be auto-marked present.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto (time attended)'), ('login', 'Check-in'), ('manual', 'Manual')], default='manual', max_length=8),
        ),
    ]
