# Generated by Django 6.0.7 on 2026-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_attendance_first_seen_at_attendance_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto (page time)'), ('teams', 'Teams report'), ('login', 'Check-in'), ('manual', 'Manual')], default='manual', max_length=8),
        ),
    ]
