# Generated by Django 6.0.7 on 2026-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_alter_attendance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_format',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'Rich text (system-authored)')], default='text', max_length=4),
        ),
        migrations.AddField(
            model_name='notification',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
