# Generated by Django 6.0.8 on 2026-08-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_feed_likes_feed_subject_notification_is_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='kind',
            field=models.CharField(choices=[('direct', 'Direct (1:1)'), ('course', 'Programme group'), ('subject', 'Subject group'), ('custom', 'Custom group')], default='custom', max_length=10),
        ),
    ]
