# Generated by Django 6.0.8 on 2026-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_alter_chatgroup_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='whatsapped',
            field=models.BooleanField(default=False, help_text='A copy reached the recipient on WhatsApp.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Also deliver a copy by WhatsApp, to the number on your contact details.'),
        ),
    ]
