# Generated by Django 6.0.8 on 2026-08-12 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_slim_registration_profile'),
        ('communication', '0017_notification_whatsapped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Sent')], db_index=True, max_length=3)),
                ('number', models.CharField(db_index=True, help_text="The person's number, digits only (2782…).", max_length=20)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('document', 'Document'), ('notification', 'Notification copy'), ('other', 'Other')], default='text', max_length=12)),
                ('body', models.TextField(blank=True)),
                ('command', models.CharField(blank=True, db_index=True, max_length=30)),
                ('wa_id', models.CharField(blank=True, db_index=True, help_text="Meta's message id — inbound de-duplication.", max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='accounts.person')),
            ],
            options={
                'verbose_name': 'WhatsApp message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['number', '-created_at'], name='communicati_number_04fb0d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('direction', 'in')), fields=('wa_id',), name='uniq_inbound_whatsapp_message')],
            },
        ),
    ]
