# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0018_whatsappmessage'),
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classsession',
            name='comm_session_subj_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='subject',
        ),
        migrations.AddField(
            model_name='announcement',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='feed',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='learning.programmemodule'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('user_type', 'A user category'), ('courses', 'Members of selected courses'), ('modules', 'Members of selected modules'), ('users', 'Specific individuals')], default='all', max_length=12),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='kind',
            field=models.CharField(choices=[('direct', 'Direct (1:1)'), ('course', 'Programme group'), ('module', 'ProgrammeModule group'), ('custom', 'Custom group')], default='custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone'), ('groups', 'My courses & modules'), ('staff', 'Staff & admins')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='subject',
            field=models.CharField(help_text='The e-mail subject line.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['module', 'session_date'], name='comm_session_subj_idx'),
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='subject',
        ),
    ]
