# Generated by Django 6.0.8 on 2026-08-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_remove_classsession_comm_session_subj_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='course',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('user_type', 'A user category'), ('modules', 'Members of selected modules'), ('users', 'Specific individuals')], default='all', max_length=12),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='kind',
            field=models.CharField(choices=[('direct', 'Direct (1:1)'), ('module', 'Module group'), ('custom', 'Custom group')], default='custom', max_length=10),
        ),
    ]
