# Generated by Django 6.0.8 on 2026-08-17 15:15

import core.storage
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0020_remove_announcement_courses_remove_chatgroup_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionattachment',
            name='file',
            field=models.FileField(storage=core.storage.files_storage, upload_to='discussions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
        migrations.AlterField(
            model_name='feed',
            name='media',
            field=models.FileField(blank=True, null=True, storage=core.storage.files_storage, upload_to='feed/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif', 'mp3', 'wav', 'm4a', 'ogg', 'mp4', 'webm', 'mov', 'm4v']), core.validators.MaxFileSize(100)]),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=core.storage.files_storage, upload_to='chat/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
        migrations.AlterField(
            model_name='workspacefile',
            name='file',
            field=models.FileField(storage=core.storage.files_storage, upload_to='workspaces/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
    ]
