# Generated by Django 6.0.8 on 2026-08-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0021_alter_discussionattachment_file_alter_feed_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto (page time)'), ('teams', 'Teams report'), ('login', 'Check-in'), ('lesson', 'Lesson studied'), ('active', 'On the platform'), ('manual', 'Manual')], default='manual', max_length=8),
        ),
    ]
