# Generated by Django 6.0.8 on 2026-08-18 08:35

import core.storage
import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0022_alter_attendance_source'),
        ('learning', '0025_alter_institution_logo_alter_lesson_author_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone on the platform'), ('institution', 'One institution'), ('programme', 'One programme'), ('cohort', 'One cohort'), ('module', 'One module'), ('private', 'Invited people only (incl. one-on-one)')], db_index=True, default='private', help_text='Who this session is for — decides both who is notified and who can see it on the calendar.', max_length=12),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='calendar_event',
            field=models.ForeignKey(blank=True, help_text='The test / exam this session prepares for or reviews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='learning.calendarevent'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='learning.cohort'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='learning.institution'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='publish_recording',
            field=models.BooleanField(default=True, help_text='Make the recording available as a past session afterwards.'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='record_automatically',
            field=models.BooleanField(default=True, help_text='Start recording the moment the host joins.'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='session_kind',
            field=models.CharField(choices=[('class', 'Class'), ('revision', 'Revision'), ('test_review', 'Test / exam review'), ('consult', 'One-on-one consultation'), ('workshop', 'Workshop'), ('briefing', 'Briefing')], default='class', max_length=12),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='teams_calendar_event_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=core.storage.files_storage, upload_to='sessions/thumbnails/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif']), core.validators.MaxFileSize(5)]),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='week',
            field=models.ForeignKey(blank=True, help_text='The week / topic this session covers, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='learning.moduleweek'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['audience', 'scheduled_start'], name='comm_meet_aud_start'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['module', 'scheduled_start'], name='comm_meet_mod_start'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['scheduled_start'], name='comm_meet_start'),
        ),
    ]
