# Generated by Django 6.0.8 on 2026-08-22 05:13

import core.storage
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0023_meetingroom_audience_meetingroom_calendar_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storage.files_storage, upload_to='feed/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif', 'mp3', 'wav', 'm4a', 'ogg', 'mp4', 'webm', 'mov', 'm4v']), core.validators.MaxFileSize(100)])),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.feed')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
