# Generated by Django 6.0.8 on 2026-10-07 07:59

import core.storage
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def mark_old_sends(apps, schema_editor):
    """Announcements sent before the composer had a status column were sent."""
    Announcement = apps.get_model('communication', 'Announcement')
    Announcement.objects.filter(sent_at__isnull=False).update(status='sent')


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0024_feedattachment'),
        ('learning', '0027_remove_moduleweek_topic_modulematerial_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='cohorts',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='learning.cohort'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='failure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='include_parents',
            field=models.BooleanField(default=False, help_text='Also send a copy to the parents/guardians of every student reached.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='learning.institution'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Deliver even to people who have switched announcements off.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='media_url',
            field=models.URLField(blank=True, help_text='A YouTube, Vimeo or other video link to play inside the notification.', max_length=500),
        ),
        migrations.AddField(
            model_name='announcement',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='url_label',
            field=models.CharField(blank=True, help_text='Button text for the link, e.g. "Open the blueprint".', max_length=60),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('targeted', 'Selected institutions, programmes, cohorts, modules or people'), ('user_type', 'A user category'), ('modules', 'Members of selected modules'), ('users', 'Specific individuals')], default='all', max_length=12),
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.storage.files_storage, upload_to='announcements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(100)])),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.announcement')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RunPython(mark_old_sends, migrations.RunPython.noop),
    ]
