# Generated by Django 6.0.8 on 2026-10-07 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0025_broadcast_composer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_assessments',
            field=models.BooleanField(default=True, help_text='A test, quiz or mock exam opening, and solutions being released.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_content',
            field=models.BooleanField(default=True, help_text='New material on your modules: blueprints, mock exams, solutions, lessons, videos.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_tasks',
            field=models.BooleanField(default=True, help_text='A task being assigned to you.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_weekly',
            field=models.BooleanField(default=True, help_text='A Monday-morning summary of the week ahead.'),
        ),
        migrations.CreateModel(
            name='AutoNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=30)),
                ('ref', models.CharField(blank=True, max_length=80)),
                ('group', models.CharField(blank=True, db_index=True, max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('level', models.CharField(default='info', max_length=10)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('dropped', models.CharField(blank=True, help_text='Why it was not sent, when it was not.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'pk'],
            },
        ),
    ]
