# Generated by Django 6.0.9 on 2026-10-08 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_backfill_login_names'),
        ('learning', '0030_cohort_class_teacher_alter_cohort_code_and_more'),
        ('orgtasks', '0009_alter_task_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False, help_text='Closed by the end-of-day job: nobody submitted it, so everyone not marked otherwise was kept present.')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_registers', to='learning.cohort')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.person')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orgtasks.task')),
            ],
            options={
                'verbose_name': 'Daily register',
                'ordering': ['-date', 'cohort__programme__grade', 'cohort__code'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=10)),
                ('reason', models.CharField(blank=True, help_text='e.g. "Sick", "Family emergency".', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parents_notified_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marks', to='accounts.person')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.person')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='attendance.dailyregister')),
            ],
            options={
                'verbose_name': 'Attendance mark',
                'ordering': ['learner__first_name', 'learner__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyregister',
            constraint=models.UniqueConstraint(fields=('cohort', 'date'), name='uniq_daily_register_per_cohort_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancemark',
            constraint=models.UniqueConstraint(fields=('register', 'learner'), name='uniq_attendance_mark_per_learner'),
        ),
    ]
