# Generated by Django 6.0.9 on 2026-10-08 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_backfill_login_names'),
        ('admissions', '0001_initial'),
        ('learning', '0029_ucs_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('final_marks', models.JSONField(blank=True, default=dict, help_text='{subject code: final %} used for the decision.')),
                ('checks', models.JSONField(blank=True, default=list, help_text='The promotion requirements and whether each was met.')),
                ('recommended', models.CharField(choices=[('pending', 'Not decided yet'), ('promote', 'Promoted to the next grade'), ('progress', 'Progressed (condoned) to the next grade'), ('retain', 'Retained in the same grade'), ('complete', 'Completed Grade 12'), ('leaving', 'Leaving the school')], default='pending', max_length=10)),
                ('outcome', models.CharField(choices=[('pending', 'Not decided yet'), ('promote', 'Promoted to the next grade'), ('progress', 'Progressed (condoned) to the next grade'), ('retain', 'Retained in the same grade'), ('complete', 'Completed Grade 12'), ('leaving', 'Leaving the school')], db_index=True, default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['programme__grade', 'person__last_name', 'person__first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-year', '-submitted_at', '-created_at'], 'verbose_name': 'Application for admission', 'verbose_name_plural': 'Applications for admission'},
        ),
        migrations.AddField(
            model_name='application',
            name='months_prepaid',
            field=models.PositiveSmallIntegerField(default=1, help_text='Months of school fees paid in advance on enrolment.'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous',
            field=models.ForeignKey(blank=True, help_text="Last year's application (returning learners).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_year', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person',
            field=models.ForeignKey(help_text='The learner this application is for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — being completed'), ('preregistered', 'Pre-registered — awaiting confirmation the learner is returning'), ('submitted', 'Submitted — pending payment'), ('documents', 'Documents outstanding'), ('review', 'Under review by the office'), ('admitted', 'Admitted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('person', 'year'), name='uniq_application_per_learner_per_year'),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='next_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_decisions', to='admissions.application'),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_decisions', to='accounts.person'),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_decisions', to='learning.programme', verbose_name='Grade'),
        ),
        migrations.AddConstraint(
            model_name='promotiondecision',
            constraint=models.UniqueConstraint(fields=('person', 'year'), name='uniq_promotion_decision_per_year'),
        ),
    ]
