# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskflag',
            name='subject',
        ),
        migrations.AddField(
            model_name='riskflag',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_flags', to='learning.programmemodule'),
        ),
        migrations.AlterField(
            model_name='reportsnapshot',
            name='scope',
            field=models.CharField(help_text='e.g. "institution", "module:12".', max_length=80),
        ),
    ]
