# Generated by Django 6.0.6 on 2026-07-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhub', '0002_event_owner_category'),
        ('reports', '0002_flexible_grading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='program',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='myhub.course'),
        ),
    ]
