# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
        ('reports', '0004_grade_cohort_average_grade_cohort_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the old (student, subject, …) constraint before the field it
        # names goes away, then re-add it on `module` once that exists.
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['module', '-final_pct']},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='subject',
        ),
        migrations.AddField(
            model_name='certificate',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='grade',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='learning.programmemodule'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='kind',
            field=models.CharField(choices=[('module', 'ProgrammeModule'), ('module', 'Module'), ('class', 'Class'), ('program', 'Program'), ('course', 'Course')], default='module', max_length=10),
        ),
        migrations.CreateModel(
            name='ModuleWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_pct', models.PositiveIntegerField(default=20)),
                ('quizzes_pct', models.PositiveIntegerField(default=10)),
                ('tests_pct', models.PositiveIntegerField(default=20)),
                ('exams_pct', models.PositiveIntegerField(default=40)),
                ('tasks_pct', models.PositiveIntegerField(default=10)),
                ('pass_mark_pct', models.PositiveIntegerField(default=50)),
                ('extra_credit_pct', models.PositiveIntegerField(default=0, help_text='Maximum bonus % that extra-credit work can add on top of the final mark.')),
                ('grade_scale', models.JSONField(blank=True, default=list, help_text='Letter-grade bands, e.g. [{"min":80,"letter":"A"}, …]. Blank = default A–F scale.')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weighting', to='learning.programmemodule')),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectWeighting',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'module')},
        ),
    ]
