# Generated by Django 6.0.8 on 2026-08-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_grade_options_remove_certificate_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='kind',
            field=models.CharField(choices=[('module', 'Module'), ('programme', 'Programme'), ('class', 'Class')], default='module', max_length=10),
        ),
    ]
