# Generated by Django 6.0.8 on 2026-08-17 15:15

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_certificate_course_alter_certificate_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'rtf', 'odt', 'ods', 'odp']), core.validators.MaxFileSize(25)]),
        ),
    ]
