# Generated by Django 6.0.8 on 2026-10-07 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def seed_computed_pct(apps, schema_editor):
    # Until now final_pct *was* the computed mark; carry it across so the staff
    # desk does not show every existing grade as computed 0%.
    Grade = apps.get_model('reports', 'Grade')
    Grade.objects.update(computed_pct=F('final_pct'))


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_certificate_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='computed_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='override_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_computed_pct, migrations.RunPython.noop),
    ]
