# Generated by Django 6.0.9 on 2026-10-08 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_cohort_class_teacher_alter_cohort_code_and_more'),
        ('reports', '0008_grade_override_certificate_revoke'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')], db_index=True)),
                ('auto_pct', models.DecimalField(blank=True, decimal_places=1, help_text='From marked quizzes, tests and assignments this term.', max_digits=5, null=True)),
                ('sba_pct', models.DecimalField(blank=True, decimal_places=1, help_text='School-Based Assessment mark for the term.', max_digits=5, null=True, verbose_name='SBA %')),
                ('exam_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Mid-year (Term 2) / final (Term 4) exam.', max_digits=5, null=True, verbose_name='Exam %')),
                ('term_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Term mark %')),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='CAPS achievement level 1 – 7.', null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — educator only'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='learning.programmemodule', verbose_name='Subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'term', 'module__order'],
                'constraints': [models.UniqueConstraint(fields=('student', 'module', 'year', 'term'), name='uniq_term_result')],
            },
        ),
    ]
