# Generated by Django 6.0.6 on 2026-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aiinsight_aireport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireport',
            name='kind',
            field=models.CharField(choices=[('meeting_minutes', 'Meeting minutes'), ('assignment', 'Generated assignment'), ('report_card', 'Report card'), ('attendance_analysis', 'Attendance analysis'), ('parent_letter', 'Parent message'), ('nl_answer', 'Ask-the-data answer'), ('secretary_briefing', 'Secretary briefing'), ('meeting_recap', 'Class recap')], db_index=True, max_length=24),
        ),
    ]
