# Generated by Django 6.0.8 on 2026-08-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_alter_aireport_kind'),
        ('learning', '0022_alter_lesson_options_remove_courseunit_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsight',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='subject',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='learning.programmemodule'),
        ),
        migrations.AddField(
            model_name='aireport',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to='learning.programmemodule'),
        ),
    ]
