# Generated by Django 6.0.8 on 2026-08-17 15:15

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_remove_aiinsight_subject_remove_aireport_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ai_uploads/', validators=[django.core.validators.FileExtensionValidator(['avif', 'csv', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'm4a', 'm4v', 'mov', 'mp3', 'mp4', 'odp', 'ods', 'odt', 'ogg', 'pdf', 'png', 'ppt', 'pptx', 'rtf', 'svg', 'txt', 'wav', 'webm', 'webp', 'xls', 'xlsx', 'zip']), core.validators.MaxFileSize(25)]),
        ),
    ]
